/**
 * Rich Authentic Culinary Recipes for Cuisine Expansion
 * Features comprehensive recipes across Indian, Spanish, Italian, Mexican, French, Japanese, Chinese, and Korean cuisines.
 */

const additionalRecipes = [
  // ─────────────────────────────────────────────
  // EXPANDED INDIAN CUISINE (BREAKFAST, LUNCH, DINNER, SNACK, DESSERT)
  // ─────────────────────────────────────────────
  {
    title: 'Crispy Masala Dosa with Sambar & Coconut Chutney',
    description: 'Golden fermented rice and lentil crepe crisped to perfection on a cast-iron griddle, filled with spiced mustard-tempered potato masala, served with piping hot vegetable sambar and fresh coconut chutney.',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 340,
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Vegan'],
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=BfyGjr4vgOc',
    isFeatured: true,
    ingredients: [
      { name: 'Fermented Dosa Batter', quantity: 4, unit: 'cups', notes: 'Rice & urad dal batter' },
      { name: 'Potatoes', quantity: 4, unit: 'medium', notes: 'Boiled and coarsely mashed' },
      { name: 'Mustard Seeds', quantity: 1, unit: 'tsp', notes: 'For tempering' },
      { name: 'Curry Leaves', quantity: 12, unit: 'leaves', notes: 'Fresh' },
      { name: 'Green Chillies', quantity: 2, unit: 'pieces', notes: 'Finely chopped' },
      { name: 'Yellow Onion', quantity: 1, unit: 'large', notes: 'Thinly sliced' },
      { name: 'Turmeric Powder', quantity: 0.5, unit: 'tsp', notes: 'For vibrant yellow color' },
      { name: 'Ghee or Sesame Oil', quantity: 3, unit: 'tbsp', notes: 'For crisping edges' },
      { name: 'Fresh Coconut Chutney', quantity: 1, unit: 'cup', notes: 'Ground with green chillies & roasted gram' },
      { name: 'Hot Vegetable Sambar', quantity: 2, unit: 'cups', notes: 'Spiced lentil stew' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Prepare the Potato Masala', instruction: 'Heat oil in a skillet; crackle mustard seeds, curry leaves, and green chillies. Sauté sliced onions until translucent. Add turmeric and salt, then fold in boiled mashed potatoes with 2 tbsp water. Cook 3 minutes.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Heat the Dosa Tawa', instruction: 'Heat a heavy flat tawa or cast-iron pan over medium-high heat. Season with a drop of oil and wipe clean with a wet paper towel.', timerMinutes: 2 },
      { stepNumber: 3, title: 'Spread and Crisp the Dosa', instruction: 'Pour a ladle of batter in the center. Using circular spiral motions from inside out, spread batter thin. Drizzle ghee around the edges and cook on medium-high until golden and crisp underneath.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Fill, Roll, and Serve', instruction: 'Place a generous spoonful of warm potato masala in the center. Fold over into a neat cylinder or triangle. Serve hot immediately with coconut chutney and sambar.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Street-Style Punjabi Samosas with Mint & Tamarind Chutney',
    description: 'Flaky, buttery pastry triangles stuffed with spiced cumin potatoes, sweet green peas, crushed coriander seeds, and whole garam masala, fried to a crisp golden amber.',
    cuisine: 'Indian',
    mealType: 'Snack',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    caloriesPerServing: 270,
    dietaryTags: ['Vegetarian', 'Vegan'],
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=9iGXHIfzNFU',
    isFeatured: true,
    ingredients: [
      { name: 'All-Purpose Flour (Maida)', quantity: 2, unit: 'cups', notes: 'Sifted' },
      { name: 'Carom Seeds (Ajwain)', quantity: 1, unit: 'tsp', notes: 'Crushed' },
      { name: 'Ghee or Warm Oil', quantity: 4, unit: 'tbsp', notes: 'For flaky moyan dough' },
      { name: 'Potatoes', quantity: 4, unit: 'large', notes: 'Boiled, peeled, cubed' },
      { name: 'Green Peas', quantity: 0.5, unit: 'cup', notes: 'Fresh or frozen' },
      { name: 'Whole Coriander Seeds', quantity: 1, unit: 'tbsp', notes: 'Coarsely crushed' },
      { name: 'Garam Masala & Amchur', quantity: 1, unit: 'tsp each', notes: 'Dry mango powder' },
      { name: 'Oil for Deep Frying', quantity: 3, unit: 'cups', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Knead Tight Pastry Dough', instruction: 'Mix flour, ajwain, salt, and ghee. Rub with fingers until crumbly. Add cold water spoon by spoon and knead into a stiff, firm dough. Rest covered for 25 minutes.', timerMinutes: 25 },
      { stepNumber: 2, title: 'Cook Spiced Potato Filling', instruction: 'In a pan, fry crushed coriander seeds, ginger, chillies, and peas. Add cubed potatoes, amchur, garam masala, and salt. Sauté 4 minutes without over-mashing.', timerMinutes: 6 },
      { stepNumber: 3, title: 'Shape and Fill Cones', instruction: 'Roll a ball of dough into an oval. Cut in half across the center. Fold straight edge into a cone, moistening edge with water. Fill with potato stuffing and seal the base firmly.', timerMinutes: 10 },
      { stepNumber: 4, title: 'Slow Fry to Golden Crisp', instruction: 'Lower samosas into warm (not boiling hot) oil. Fry on low-medium heat for 12-15 minutes until pale golden and ultra-crisp. Drain on paper towels.', timerMinutes: 15 },
    ],
  },
  {
    title: 'Slow-Cooked Bukhara Dal Makhani (Black Lentils)',
    description: 'Iconic North Indian black urad lentils and kidney beans slow-simmered for 8 hours with fragrant ginger, garlic, ripe tomato reduction, cultured butter, and fresh cream.',
    cuisine: 'Indian',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    caloriesPerServing: 390,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=DH5KrmmugIY',
    isFeatured: true,
    ingredients: [
      { name: 'Whole Black Urad Dal', quantity: 1, unit: 'cup', notes: 'Soaked overnight (8 hours)' },
      { name: 'Rajma (Kidney Beans)', quantity: 0.25, unit: 'cup', notes: 'Soaked overnight' },
      { name: 'Ripe Red Tomatoes', quantity: 4, unit: 'large', notes: 'Pureed smooth' },
      { name: 'Ginger Garlic Paste', quantity: 2, unit: 'tbsp', notes: 'Freshly pounded' },
      { name: 'Kashmiri Red Chilli Powder', quantity: 1.5, unit: 'tbsp', notes: 'For rich red color' },
      { name: 'Unsalted Butter', quantity: 60, unit: 'g', notes: 'Divided throughout cooking' },
      { name: 'Heavy Cream', quantity: 0.25, unit: 'cup', notes: 'Swirled at finish' },
      { name: 'Kasoori Methi', quantity: 1, unit: 'tsp', notes: 'Toasted and crushed' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Pressure Cook Lentils', instruction: 'Pressure cook soaked urad dal and rajma with 4 cups water, salt, and 1 tsp Kashmiri chilli powder for 6-8 whistles until meltingly tender.', timerMinutes: 25 },
      { stepNumber: 2, title: 'Prepare the Butter Gravy', instruction: 'Melt half the butter in a heavy pot. Add ginger-garlic paste and sauté 1 minute. Pour tomato puree and simmer until butter floats on top.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Slow Mash and Simmer', instruction: 'Add cooked lentils with their cooking water. Mash lentils against the side of the pot using a wooden masher. Simmer on low flame for 30 minutes, stirring frequently.', timerMinutes: 30 },
      { stepNumber: 4, title: 'Finish with Cream and Butter', instruction: 'Stir in remaining butter, heavy cream, and crushed kasoori methi. Simmer 5 more minutes until velvety and rich. Serve with garlic butter naan.', timerMinutes: 5 },
    ],
  },
  {
    title: 'Restaurant-Style Tandoori Paneer Tikka with Mint Raita',
    description: 'Succulent cubes of fresh cottage cheese, bell peppers, and red onions marinated in hung yogurt, mustard oil, carom seeds, and smoked Kashmiri spices, charred over high heat.',
    cuisine: 'Indian',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 350,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=DmX62cMb2H0',
    isFeatured: false,
    ingredients: [
      { name: 'Fresh Paneer', quantity: 400, unit: 'g', notes: 'Cut into thick 1-inch cubes' },
      { name: 'Bell Peppers (Assorted Colors)', quantity: 2, unit: 'medium', notes: 'Cut into 1-inch squares' },
      { name: 'Red Onion', quantity: 1, unit: 'large', notes: 'Cut into petals' },
      { name: 'Hung Curd (Thick Yogurt)', quantity: 0.75, unit: 'cup', notes: 'Drained Greek yogurt' },
      { name: 'Mustard Oil (Heated)', quantity: 2, unit: 'tbsp', notes: 'For authentic tandoori aroma' },
      { name: 'Roasted Gram Flour (Besan)', quantity: 2, unit: 'tbsp', notes: 'Helps marinade cling' },
      { name: 'Kashmiri Chilli & Chaat Masala', quantity: 1.5, unit: 'tsp each', notes: '' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Whisk the Tandoori Marinade', instruction: 'In a wide bowl, whisk hung curd, hot mustard oil, roasted besan, ginger-garlic paste, Kashmiri chilli, garam masala, and lemon juice until velvety.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Coat Paneer & Veggies', instruction: 'Gently fold in paneer cubes, onion petals, and bell peppers until thoroughly coated. Let rest for 20 minutes.', timerMinutes: 20 },
      { stepNumber: 3, title: 'Thread onto Skewers', instruction: 'Thread alternating bell pepper, onion, and paneer cubes onto soaked wooden or metal skewers.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Grill or Pan Sear', instruction: 'Grill in oven at 220°C (430°F) or pan-sear on a smoking skillet with butter for 10-12 minutes, turning until edges are smoky and charred. Sprinkle chaat masala.', timerMinutes: 12 },
    ],
  },
  {
    title: 'Amritsari Chana Masala with Spiced Pickled Onions',
    description: 'Hearty white chickpeas steeped in dark tea water, simmered with pomegranate seeds (anardana), dry roasted spices, and ginger juliennes — the legendary pride of Punjab.',
    cuisine: 'Indian',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    caloriesPerServing: 320,
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=KBsqb_MJk1Y',
    isFeatured: false,
    ingredients: [
      { name: 'White Chickpeas (Kabuli Chana)', quantity: 1.5, unit: 'cups', notes: 'Soaked 8 hours with tea bag for dark color' },
      { name: 'Anardana (Dry Pomegranate Seeds)', quantity: 1, unit: 'tbsp', notes: 'Crushed, for tangy bite' },
      { name: 'Onions', quantity: 2, unit: 'medium', notes: 'Finely chopped' },
      { name: 'Tomatoes', quantity: 2, unit: 'medium', notes: 'Finely chopped' },
      { name: 'Ginger Juliennes & Green Chillies', quantity: 2, unit: 'tbsp', notes: 'For garnish and base' },
      { name: 'Chana Masala Spice Blend', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Ghee or Mustard Oil', quantity: 2, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Boil Chickpeas', instruction: 'Boil soaked chickpeas with a black tea bag, cinnamon stick, black cardamom, and salt until melt-in-your-mouth soft. Discard tea bag.', timerMinutes: 20 },
      { stepNumber: 2, title: 'Sauté Aromatics', instruction: 'Heat ghee in a pan. Sauté cumin and chopped onions until deep golden. Add ginger, garlic, tomatoes, and crushed anardana. Cook until oil separates.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Simmer Chickpeas', instruction: 'Add boiled chickpeas along with their stock. Mash a few chickpeas with the back of a ladle to thicken gravy. Simmer for 15 minutes.', timerMinutes: 15 },
      { stepNumber: 4, title: 'Ghee Ginger Tadka', instruction: 'Heat 1 tbsp ghee in a ladle with ginger juliennes and green chillies. Pour smoking over the curry. Garnish with fresh cilantro.', timerMinutes: 3 },
    ],
  },
  {
    title: 'Kashmiri Mutton Rogan Josh',
    description: 'Tender braised lamb or goat shanks slow-simmered in an intensely aromatic gravy colored by dried Kashmiri cockscomb flower (Ratan Jot) and spiced with fennel and dry ginger.',
    cuisine: 'Indian',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    caloriesPerServing: 560,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=Ri-oRBSB0Zw',
    isFeatured: true,
    ingredients: [
      { name: 'Mutton / Lamb Shanks', quantity: 800, unit: 'g', notes: 'Bone-in cuts' },
      { name: 'Mustard Oil', quantity: 4, unit: 'tbsp', notes: 'Smoked and cooled slightly' },
      { name: 'Greek Yogurt (Whisked)', quantity: 0.75, unit: 'cup', notes: 'Room temperature' },
      { name: 'Kashmiri Red Chilli Powder', quantity: 2, unit: 'tbsp', notes: 'Whisked with water into paste' },
      { name: 'Saunf (Fennel Powder)', quantity: 1.5, unit: 'tbsp', notes: 'Freshly ground' },
      { name: 'Sonth (Dry Ginger Powder)', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Asafoetida (Hing)', quantity: 1, unit: 'pinch', notes: '' },
      { name: 'Whole Spices (Cloves, Green & Black Cardamom)', quantity: 1, unit: 'set', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Sear Meat in Mustard Oil', instruction: 'Heat mustard oil to smoking point, cool slightly. Fry whole spices and hing, then add mutton pieces. Sear over high heat until browned.', timerMinutes: 10 },
      { stepNumber: 2, title: 'Add Kashmiri Chilli Paste', instruction: 'Stir in Kashmiri chilli paste with a splash of water so it does not burn. Sauté until oil turns deep ruby red.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Fold in Yogurt & Spices', instruction: 'Turn flame to low. Whisk in yogurt continuously to prevent curdling. Add fennel powder, dry ginger, and salt.', timerMinutes: 8 },
      { stepNumber: 4, title: 'Slow Braise', instruction: 'Add 1.5 cups warm water. Cover and slow braise on low flame for 45-60 minutes until meat falls easily from bone. Serve with steamed basmati rice.', timerMinutes: 55 },
    ],
  },
  {
    title: 'Homestyle Indori Poha with Crispy Sev & Peanuts',
    description: 'Fluffy steamed flattened rice tempered with mustard seeds, crunchy roasted peanuts, green chillies, onions, and finished with fresh pomegranate pearls, spicy sev, and lime.',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    caloriesPerServing: 240,
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Vegan'],
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=xRYuopk57SM',
    isFeatured: false,
    ingredients: [
      { name: 'Thick Poha (Flattened Rice)', quantity: 2.5, unit: 'cups', notes: 'Rinsed in colander, drained 5 mins' },
      { name: 'Raw Peanuts', quantity: 0.25, unit: 'cup', notes: 'Fried golden' },
      { name: 'Yellow Onion', quantity: 1, unit: 'medium', notes: 'Finely chopped' },
      { name: 'Green Chillies', quantity: 2, unit: 'pieces', notes: 'Slit' },
      { name: 'Mustard Seeds & Curry Leaves', quantity: 1, unit: 'tsp each', notes: 'For tadka' },
      { name: 'Turmeric Powder & Sugar', quantity: 0.5, unit: 'tsp each', notes: '' },
      { name: 'Crispy Ratlami Sev', quantity: 0.5, unit: 'cup', notes: 'For crunchy topping' },
      { name: 'Fresh Coriander & Lime', quantity: 1, unit: 'set', notes: 'For garnish' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Rinse Poha', instruction: 'Rinse poha gently under cold running water in a colander. Toss lightly with salt and sugar. Let drain 5 minutes until soft and fluffy.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Fry Peanuts & Aromatics', instruction: 'Heat 2 tbsp oil in a pan. Fry peanuts until crisp; set half aside for topping. Add mustard seeds, green chillies, curry leaves, and onions. Sauté until translucent.', timerMinutes: 4 },
      { stepNumber: 3, title: 'Toss Poha with Turmeric', instruction: 'Add turmeric powder, stir. Gently fold in drained poha. Cover and steam on lowest heat for 3 minutes.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Garnish and Serve', instruction: 'Squeeze fresh lime juice. Top with crunchy fried peanuts, crispy sev, chopped coriander, and pomegranate arils. Serve piping hot with chai.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Warm Gulab Jamun in Rose-Cardamom Saffron Syrup',
    description: 'Golden fried dumplings made from reduced milk solids (khoya) and paneer, soaked in warm rose water and saffron scented sugar syrup — the queen of Indian festivities.',
    cuisine: 'Indian',
    mealType: 'Dessert',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 20,
    cookTime: 20,
    servings: 6,
    caloriesPerServing: 330,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=qlHTfoMinMU',
    isFeatured: false,
    ingredients: [
      { name: 'Fresh Soft Mawa / Khoya', quantity: 200, unit: 'g', notes: 'Grated smooth' },
      { name: 'Soft Paneer', quantity: 50, unit: 'g', notes: 'Crumbled & mashed smooth' },
      { name: 'All-Purpose Flour (Maida)', quantity: 3, unit: 'tbsp', notes: 'For binding' },
      { name: 'Baking Powder', quantity: 0.25, unit: 'tsp', notes: '' },
      { name: 'Sugar', quantity: 1.5, unit: 'cups', notes: 'For syrup' },
      { name: 'Water', quantity: 1.5, unit: 'cups', notes: 'For syrup' },
      { name: 'Green Cardamom Pods & Saffron', quantity: 1, unit: 'set', notes: 'For fragrant syrup' },
      { name: 'Rose Water', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Ghee or Oil', quantity: 2, unit: 'cups', notes: 'For slow gentle frying' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Boil Aromatic Sugar Syrup', instruction: 'Boil sugar and water with crushed cardamom pods and saffron for 7-8 minutes until slightly sticky (half-string consistency). Stir in rose water and keep warm.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Knead Silky Dough', instruction: 'Combine grated khoya, mashed paneer, flour, and baking powder. Knead with palm for 5 minutes until completely crack-free and silky smooth.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Roll and Slow Fry', instruction: 'Roll into 16 smooth, crack-free bite-sized balls. Heat ghee over low-medium heat. Gently slide balls into ghee and fry slowly for 10-12 minutes until evenly deep brown.', timerMinutes: 12 },
      { stepNumber: 4, title: 'Soak in Syrup', instruction: 'Transfer hot fried jamuns directly into warm sugar syrup. Let soak for at least 2 hours so they become tender and juicy throughout.', timerMinutes: 120 },
    ],
  },
  {
    title: 'Classic Chicken Tikka Masala with Garlic Naan',
    description: 'Marinated roasted boneless chicken chunks swimming in a creamy, richly spiced orange-red tomato sauce packed with fenugreek and heavy cream.',
    cuisine: 'Indian',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    caloriesPerServing: 590,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=wm5vqZcl8BQ',
    isFeatured: true,
    ingredients: [
      { name: 'Chicken Breast or Thighs', quantity: 650, unit: 'g', notes: 'Cut into bite-sized cubes' },
      { name: 'Greek Yogurt', quantity: 0.5, unit: 'cup', notes: 'For marinade' },
      { name: 'Garam Masala & Cumin', quantity: 1, unit: 'tbsp each', notes: '' },
      { name: 'Crushed San Marzano Tomatoes', quantity: 400, unit: 'g', notes: '' },
      { name: 'Heavy Cream', quantity: 0.5, unit: 'cup', notes: '' },
      { name: 'Butter', quantity: 40, unit: 'g', notes: '' },
      { name: 'Garlic & Ginger', quantity: 2, unit: 'tbsp', notes: 'Minced' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Marinate & Broil Chicken', instruction: 'Marinate chicken in spiced yogurt for 30 minutes. Broil under oven broiler for 12 minutes until nicely charred on edges.', timerMinutes: 15 },
      { stepNumber: 2, title: 'Build Masala Sauce', instruction: 'Melt butter; sauté onions, garlic, and ginger until fragrant. Add tomatoes, cumin, coriander, and chilli. Simmer 12 minutes.', timerMinutes: 12 },
      { stepNumber: 3, title: 'Blend & Simmer', instruction: 'Blend sauce until silky smooth. Return to skillet, add charred chicken pieces and heavy cream. Simmer 6 minutes. Serve with hot garlic naan.', timerMinutes: 8 },
    ],
  },

  // ─────────────────────────────────────────────
  // SPANISH CUISINE (PAELLA, TAPAS, DESSERT)
  // ─────────────────────────────────────────────
  {
    title: 'Traditional Seafood Paella Valenciana',
    description: 'Iconic Spanish saffron rice simmered in rich seafood broth, loaded with jumbo prawns, tender calamari rings, Mediterranean black mussels, sweet bell peppers, and sweet green peas with crispy socarrat crust.',
    cuisine: 'Spanish',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 25,
    cookTime: 35,
    servings: 4,
    caloriesPerServing: 520,
    dietaryTags: ['Pescatarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=vNBuXsTY15E',
    isFeatured: true,
    ingredients: [
      { name: 'Bomba Rice (or Calasparra)', quantity: 350, unit: 'g', notes: 'Short-grain Spanish paella rice' },
      { name: 'Jumbo Tiger Prawns', quantity: 8, unit: 'large', notes: 'Shell-on for flavor' },
      { name: 'Calamari / Squid', quantity: 250, unit: 'g', notes: 'Cleaned and sliced into rings' },
      { name: 'Fresh Mussels', quantity: 12, unit: 'pieces', notes: 'Scrubbed and debearded' },
      { name: 'Seafood or Fish Stock', quantity: 4, unit: 'cups', notes: 'Piping hot' },
      { name: 'Spanish Saffron Strands', quantity: 0.5, unit: 'tsp', notes: 'Steeped in 2 tbsp warm broth' },
      { name: 'Sweet Smoked Paprika (Pimentón)', quantity: 1, unit: 'tbsp', notes: 'Dulce' },
      { name: 'Grated Fresh Tomatoes', quantity: 2, unit: 'medium', notes: 'Grated flesh without skin' },
      { name: 'Extra Virgin Olive Oil', quantity: 4, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Sear Seafood', instruction: 'Heat olive oil in a wide 14-inch paella pan. Sear prawns and calamari 2 minutes per side until pink. Transfer to a plate.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Create Sofrito Base', instruction: 'In same oil, sauté diced onions, garlic, and red peppers. Add grated tomatoes and smoked paprika. Cook down until thick and dark.', timerMinutes: 8 },
      { stepNumber: 3, title: 'Toast Rice & Pour Broth', instruction: 'Add Bomba rice and stir 2 minutes to coat with sofrito. Pour in hot saffron broth. Shake pan gently to distribute rice evenly — do NOT stir again.', timerMinutes: 10 },
      { stepNumber: 4, title: 'Arrange Seafood & Form Socarrat', instruction: 'Nestle prawns, calamari, and mussels into the rice. Simmer 12 minutes until broth is absorbed. Increase heat for 2 minutes to create crispy socarrat at bottom. Rest 5 minutes before serving with lemon wedges.', timerMinutes: 15 },
    ],
  },
  {
    title: 'Classic Spanish Tortilla Española (Potato Omelette)',
    description: 'The golden centerpiece of Spanish tapas: tender olive-oil poached Yukon gold potatoes and caramelized sweet onions folded into velvety farm-fresh eggs.',
    cuisine: 'Spanish',
    mealType: 'Breakfast',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    caloriesPerServing: 310,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=epIdjMaHa_w',
    isFeatured: false,
    ingredients: [
      { name: 'Yukon Gold Potatoes', quantity: 600, unit: 'g', notes: 'Peeled and sliced thinly into 1/8-inch rounds' },
      { name: 'Farm Eggs', quantity: 6, unit: 'large', notes: 'Lightly whisked' },
      { name: 'Sweet Yellow Onion', quantity: 1, unit: 'large', notes: 'Thinly sliced' },
      { name: 'Extra Virgin Spanish Olive Oil', quantity: 1, unit: 'cup', notes: 'For slow poaching' },
      { name: 'Flaky Sea Salt', quantity: 1, unit: 'tsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Poach Potatoes & Onions', instruction: 'Submerge potato slices and onions in warm olive oil over medium-low heat. Cook gently 15 minutes until tender without browning. Drain oil (reserve for dressing).', timerMinutes: 15 },
      { stepNumber: 2, title: 'Combine with Eggs', instruction: 'Whisk eggs with salt in a bowl. Gently fold in warm drained potatoes and onions. Let rest 10 minutes to absorb flavor.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Cook and Flip', instruction: 'Heat 1 tbsp reserved oil in an 8-inch nonstick pan over medium heat. Pour in egg mixture. Shake pan to round edges. When bottom is golden, place a flat plate over pan and flip swiftly.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Finish Second Side', instruction: 'Slide back into pan and cook 2 minutes more for a moist, creamy center. Serve warm or at room temperature.', timerMinutes: 3 },
    ],
  },
  {
    title: 'Crispy Patatas Bravas with Spicy Paprika Sauce & Garlic Aioli',
    description: 'Golden fried Spanish potato cubes with crispy blistered skin and fluffy centers, smothered in spicy tomato-paprika brava sauce and rich garlic aioli.',
    cuisine: 'Spanish',
    mealType: 'Snack',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    caloriesPerServing: 280,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=XIrfkLCTBsE',
    isFeatured: false,
    ingredients: [
      { name: 'Russet Potatoes', quantity: 3, unit: 'large', notes: 'Cut into bite-sized 1-inch rough cubes' },
      { name: 'Olive Oil for Frying', quantity: 2, unit: 'cups', notes: '' },
      { name: 'Smoked Hot Paprika (Pimentón Picante)', quantity: 1, unit: 'tbsp', notes: '' },
      { name: 'Tomato Paste', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Garlic Cloves', quantity: 4, unit: 'cloves', notes: 'Grated for aioli' },
      { name: 'Mayonnaise', quantity: 0.5, unit: 'cup', notes: 'For quick aioli' },
      { name: 'Sherry Vinegar', quantity: 1, unit: 'tsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Parboil Potatoes', instruction: 'Boil potato cubes in salted water with 1/2 tsp baking soda for 6 minutes. Drain and rough up edges in colander for extra crispness.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Make Spicy Brava Sauce', instruction: 'Warm olive oil, toast paprika and flour 1 minute. Whisk in tomato paste, broth, and sherry vinegar. Simmer until thickened.', timerMinutes: 6 },
      { stepNumber: 3, title: 'Fry Potatoes to Golden Perfection', instruction: 'Fry potatoes in 360°F (180°C) oil until deep golden and crackling crisp, about 7 minutes. Drain and season with sea salt.', timerMinutes: 7 },
      { stepNumber: 4, title: 'Drizzle & Serve', instruction: 'Pile hot crispy potatoes on a plate. Drizzle liberally with warm brava sauce and dollops of garlic aioli. Serve with toothpicks.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Spanish Churros con Chocolate',
    description: 'Crisp fluted fried pastry sticks rolled in cinnamon sugar, served with a velvety, thick dipping sauce made from rich dark Spanish chocolate.',
    cuisine: 'Spanish',
    mealType: 'Dessert',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 360,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1624300629298-e9de39c13be5?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=lDnMT_lIJnk',
    isFeatured: true,
    ingredients: [
      { name: 'Water', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Unsalted Butter', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'All-Purpose Flour', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Eggs', quantity: 2, unit: 'large', notes: '' },
      { name: 'Granulated Sugar & Cinnamon', quantity: 0.5, unit: 'cup', notes: 'For coating' },
      { name: 'Dark Chocolate (70%)', quantity: 150, unit: 'g', notes: 'Chopped' },
      { name: 'Whole Milk or Cream', quantity: 1, unit: 'cup', notes: 'For chocolate dip' },
      { name: 'Cornstarch', quantity: 1, unit: 'tsp', notes: 'To thicken chocolate' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Choux Dough', instruction: 'Boil water, butter, and sugar. Stir in flour all at once over medium heat until dough pulls away into a ball. Cool slightly, then beat in eggs one at a time.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Simmer Thick Chocolate Dip', instruction: 'Warm milk with cornstarch and chopped dark chocolate, whisking constantly until luscious, glossy, and thick.', timerMinutes: 6 },
      { stepNumber: 3, title: 'Pipe and Fry Churros', instruction: 'Pipe dough through a star tip directly into 375°F (190°C) hot oil in 6-inch strips. Fry 3-4 minutes until golden amber.', timerMinutes: 6 },
      { stepNumber: 4, title: 'Roll in Cinnamon Sugar', instruction: 'Roll hot churros immediately in cinnamon sugar. Serve steaming with warm chocolate dipping sauce.', timerMinutes: 2 },
    ],
  },

  // ─────────────────────────────────────────────
  // EXPANDED ITALIAN CUISINE
  // ─────────────────────────────────────────────
  {
    title: 'Creamy Tuscan Garlic Chicken with Sun-Dried Tomatoes',
    description: 'Pan-seared chicken cutlets bathed in a velvety garlic, white wine, baby spinach, and sweet sun-dried tomato parmesan cream sauce.',
    cuisine: 'Italian',
    mealType: 'Dinner',
    difficulty: 'Easy',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    caloriesPerServing: 510,
    dietaryTags: ['Gluten-Free', 'Keto'],
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dGPSferXkVA',
    isFeatured: true,
    ingredients: [
      { name: 'Boneless Chicken Breasts', quantity: 600, unit: 'g', notes: 'Sliced horizontally into cutlets' },
      { name: 'Garlic Cloves', quantity: 5, unit: 'cloves', notes: 'Minced' },
      { name: 'Sun-Dried Tomatoes in Oil', quantity: 0.5, unit: 'cup', notes: 'Drained and sliced' },
      { name: 'Fresh Baby Spinach', quantity: 3, unit: 'cups', notes: '' },
      { name: 'Heavy Cream', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Parmigiano Reggiano', quantity: 0.5, unit: 'cup', notes: 'Freshly grated' },
      { name: 'Dry White Wine', quantity: 0.25, unit: 'cup', notes: 'Pinot Grigio or broth' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Sear Chicken', instruction: 'Season chicken cutlets with Italian herbs and sear in olive oil for 4 minutes per side until golden. Set aside.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Sauté Aromatics', instruction: 'Sauté minced garlic and sun-dried tomatoes 1 minute. Deglaze skillet with white wine, scraping up flavorful browned bits.', timerMinutes: 3 },
      { stepNumber: 3, title: 'Simmer Cream Sauce', instruction: 'Pour in heavy cream and chicken broth. Bring to a gentle simmer. Stir in parmesan and baby spinach until wilted.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Combine and Serve', instruction: 'Return seared chicken to the skillet with resting juices. Simmer 3 minutes. Garnish with fresh basil leaves.', timerMinutes: 4 },
    ],
  },
  {
    title: 'Classic Italian Espresso Tiramisu',
    description: 'Crisp Italian savoiardi ladyfingers soaked in dark espresso and marsala wine, layered between pillows of sweet mascarpone cream and dusted with Dutch cocoa.',
    cuisine: 'Italian',
    mealType: 'Dessert',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 25,
    cookTime: 0,
    servings: 8,
    caloriesPerServing: 420,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=7VTtenyKRg4',
    isFeatured: true,
    ingredients: [
      { name: 'Mascarpone Cheese', quantity: 450, unit: 'g', notes: 'Room temperature' },
      { name: 'Italian Ladyfingers (Savoiardi)', quantity: 24, unit: 'pieces', notes: '' },
      { name: 'Fresh Egg Yolks', quantity: 4, unit: 'large', notes: 'Free-range' },
      { name: 'Brewed Strong Espresso', quantity: 1.5, unit: 'cups', notes: 'Cooled' },
      { name: 'Marsala Wine (or Kahlua)', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Dutch Cocoa Powder', quantity: 3, unit: 'tbsp', notes: 'For dusting' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Whip Sabayon', instruction: 'Whisk egg yolks and sugar over a double boiler until pale, thick, and tripled in volume (about 5 minutes). Cool slightly.', timerMinutes: 6 },
      { stepNumber: 2, title: 'Fold Mascarpone', instruction: 'Gently fold room-temperature mascarpone into the yolk mixture until velvety and smooth. Fold in whipped egg whites or heavy cream.', timerMinutes: 4 },
      { stepNumber: 3, title: 'Dip Ladyfingers & Layer', instruction: 'Combine espresso and marsala. Quickly dip ladyfingers (1 second each) and arrange as base in a 9x9 inch dish. Spread half the cream. Repeat layer.', timerMinutes: 10 },
      { stepNumber: 4, title: 'Chill & Cocoa Dust', instruction: 'Refrigerate for at least 6 hours (or overnight). Dust with generous unsweetened cocoa powder just before serving.', timerMinutes: 360 },
    ],
  },

  // ─────────────────────────────────────────────
  // EXPANDED ASIAN CUISINE (JAPANESE & KOREAN)
  // ─────────────────────────────────────────────
  {
    title: 'Authentic Japanese Tonkotsu Pork Ramen',
    description: 'Springy ramen noodles in a milky 12-hour rich pork bone broth, topped with tender braised chashu pork belly, a ramen egg (ajitsuke tamago), wood ear mushrooms, and nori.',
    cuisine: 'Japanese',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 30,
    cookTime: 45,
    servings: 2,
    caloriesPerServing: 680,
    dietaryTags: [],
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=lyVINyzHh9M',
    isFeatured: true,
    ingredients: [
      { name: 'Fresh Ramen Noodles', quantity: 300, unit: 'g', notes: 'Wavy or straight' },
      { name: 'Tonkotsu Rich Broth', quantity: 4, unit: 'cups', notes: 'Simmered pork bone broth' },
      { name: 'Braised Pork Chashu Slices', quantity: 6, unit: 'slices', notes: 'Torched before serving' },
      { name: 'Marinated Ramen Egg (Ajitama)', quantity: 2, unit: 'pieces', notes: 'Soft-boiled, jammy yolk' },
      { name: 'Nori Seaweed Sheets', quantity: 2, unit: 'sheets', notes: '' },
      { name: 'Green Scallions', quantity: 3, unit: 'stalks', notes: 'Finely sliced' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Heat Broth & Tare', instruction: 'Warm soy sauce tare and ladle piping hot tonkotsu broth into pre-warmed ramen bowls.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Boil Noodles', instruction: 'Cook fresh ramen noodles in boiling water for exactly 90 seconds. Shake water off vigorously.', timerMinutes: 2 },
      { stepNumber: 3, title: 'Fold Noodles into Broth', instruction: 'Slide noodles into hot broth and fold with chopsticks to aerate and coat.', timerMinutes: 1 },
      { stepNumber: 4, title: 'Arrange Toppings', instruction: 'Top with seared chashu slices, halved ramen egg, sliced scallions, and nori sheets. Serve immediately piping hot.', timerMinutes: 3 },
    ],
  },
  {
    title: 'Korean Dolsot Bibimbap with Crispy Rice & Gochujang',
    description: 'Sizzling hot stone bowl filled with crispy sesame rice, seasoned spinach, shredded carrots, shiitake mushrooms, bean sprouts, and a sunny egg with sweet spicy gochujang.',
    cuisine: 'Korean',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 25,
    cookTime: 15,
    servings: 2,
    caloriesPerServing: 480,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=_wYahmPULr8',
    isFeatured: true,
    ingredients: [
      { name: 'Cooked Short-Grain Rice', quantity: 3, unit: 'cups', notes: 'Warm' },
      { name: 'Toasted Sesame Oil', quantity: 2, unit: 'tbsp', notes: 'To coat hot stone bowl' },
      { name: 'Korean Gochujang Paste', quantity: 2, unit: 'tbsp', notes: 'Mixed with honey & sesame' },
      { name: 'Shiitake Mushrooms', quantity: 1, unit: 'cup', notes: 'Sliced & sautéed' },
      { name: 'Soybean Sprouts & Spinach', quantity: 1, unit: 'cup each', notes: 'Blanched & sesame dressed' },
      { name: 'Farm Eggs', quantity: 2, unit: 'large', notes: 'Sunny-side up' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Sauté Seasoned Vegetables', instruction: 'Quickly sauté julienned carrots, seasoned spinach, bean sprouts, and sliced shiitakes separately with sesame oil and garlic.', timerMinutes: 10 },
      { stepNumber: 2, title: 'Crisp the Rice', instruction: 'Brush bottom and sides of stone bowl with generous sesame oil. Press cooked rice into the bowl and heat over medium flame until rice crackles and crisps.', timerMinutes: 8 },
      { stepNumber: 3, title: 'Arrange Bibimbap & Sauce', instruction: 'Artfully arrange mounds of each vegetable over the rice. Top with a fried egg and a generous dollop of gochujang sauce. Mix vigorously at table.', timerMinutes: 4 },
    ],
  },
];

module.exports = additionalRecipes;
