const mongoose = require('mongoose');
const User = require('../models/User');
const Recipe = require('../models/Recipe');
const additionalRecipes = require('./additionalRecipes');

const baseRecipes = [
  // ─────────────────────────────────────────────
  // ITALIAN RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Authentic Creamy Spaghetti Carbonara',
    description: 'A Roman pasta classic featuring al dente spaghetti, golden crispy guanciale, velvety egg yolk and pecorino romano emulsion, finished with freshly cracked black pepper.',
    cuisine: 'Italian',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 580,
    dietaryTags: [],
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=D_2DBLAt57c',
    isFeatured: true,
    ingredients: [
      { name: 'Spaghetti Pasta', quantity: 400, unit: 'g', notes: 'Bronze-die extruded preferred' },
      { name: 'Guanciale (or Pancetta)', quantity: 200, unit: 'g', notes: 'Thick cut, cubed' },
      { name: 'Fresh Egg Yolks', quantity: 4, unit: 'large', notes: 'Room temperature' },
      { name: 'Whole Egg', quantity: 1, unit: 'large', notes: 'Free-range' },
      { name: 'Pecorino Romano Cheese', quantity: 80, unit: 'g', notes: 'Freshly grated' },
      { name: 'Parmigiano Reggiano', quantity: 40, unit: 'g', notes: 'Freshly grated' },
      { name: 'Coarse Black Peppercorns', quantity: 1, unit: 'tbsp', notes: 'Freshly crushed' },
      { name: 'Kosher Salt', quantity: 1, unit: 'pinch', notes: 'For pasta water' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Boil Pasta Water', instruction: 'Bring a large pot of water to a rolling boil. Salt lightly. Cook spaghetti 2 minutes shy of al dente.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Crisp the Guanciale', instruction: 'In a wide skillet over medium-low heat, gently fry cubed guanciale until golden and crispy, rendering out the fragrant fat. Remove from heat.', timerMinutes: 6 },
      { stepNumber: 3, title: 'Whisk the Egg & Cheese Cream', instruction: 'Vigorously whisk 4 yolks, 1 whole egg, grated Pecorino, Parmigiano, and half the pepper until thick and glossy.', timerMinutes: 2 },
      { stepNumber: 4, title: 'Emulsify and Serve', instruction: 'Transfer spaghetti to guanciale skillet with a splash of starchy pasta water. Let cool slightly, then pour in egg mixture while stirring rapidly to create silky crema. Garnish with cheese and crushed pepper.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Classic Margherita Pizza Napoletana',
    description: 'The iconic Neapolitan pizza with hand-stretched sourdough crust, San Marzano tomato sauce, fresh fior di latte mozzarella, and fragrant fresh basil leaves.',
    cuisine: 'Italian',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 20,
    cookTime: 12,
    servings: 4,
    caloriesPerServing: 480,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=sv3TXMSv6Lw',
    isFeatured: true,
    ingredients: [
      { name: 'Pizza Dough Ball', quantity: 500, unit: 'g', notes: '72-hour cold fermented' },
      { name: 'San Marzano Canned Tomatoes', quantity: 400, unit: 'g', notes: 'Hand-crushed, uncooked sauce' },
      { name: 'Fresh Fior di Latte Mozzarella', quantity: 250, unit: 'g', notes: 'Torn into pieces' },
      { name: 'Fresh Basil Leaves', quantity: 1, unit: 'handful', notes: 'Added after baking' },
      { name: 'Extra Virgin Olive Oil', quantity: 2, unit: 'tbsp', notes: 'For drizzling' },
      { name: 'Fine Sea Salt', quantity: 1, unit: 'tsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Preheat Oven', instruction: 'Place a pizza stone or steel in oven and preheat to maximum heat (500°F/260°C) for at least 45 minutes.', timerMinutes: 45 },
      { stepNumber: 2, title: 'Stretch the Dough', instruction: 'On a lightly floured surface, gently stretch dough by hand into a 12-inch circle, keeping edges slightly thicker.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Top the Pizza', instruction: 'Spread crushed tomatoes evenly. Season with salt. Scatter torn mozzarella. Drizzle with olive oil.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Bake and Finish', instruction: 'Slide pizza onto hot stone. Bake 8-12 minutes until crust is charred in spots and cheese is bubbling. Top with fresh basil immediately.', timerMinutes: 10 },
    ],
  },
  {
    title: 'Homemade Lasagna al Forno',
    description: 'Layers of fresh egg pasta sheets, slow-cooked Bolognese meat ragù, silky béchamel sauce, and generous Parmigiano Reggiano, oven-baked to golden perfection.',
    cuisine: 'Italian',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 40,
    cookTime: 60,
    servings: 6,
    caloriesPerServing: 720,
    dietaryTags: [],
    image: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=CWg_Rhgqxfc',
    isFeatured: false,
    ingredients: [
      { name: 'Lasagna Pasta Sheets', quantity: 300, unit: 'g', notes: 'Fresh or dried' },
      { name: 'Ground Beef', quantity: 400, unit: 'g', notes: '80/20 fat ratio' },
      { name: 'Ground Pork', quantity: 200, unit: 'g', notes: 'For ragu richness' },
      { name: 'San Marzano Tomatoes', quantity: 400, unit: 'g', notes: 'Crushed' },
      { name: 'Whole Milk', quantity: 3, unit: 'cups', notes: 'For béchamel' },
      { name: 'Butter', quantity: 4, unit: 'tbsp', notes: 'For béchamel' },
      { name: 'All-Purpose Flour', quantity: 4, unit: 'tbsp', notes: 'For béchamel' },
      { name: 'Parmigiano Reggiano', quantity: 150, unit: 'g', notes: 'Freshly grated, divided' },
      { name: 'Yellow Onion', quantity: 1, unit: 'medium', notes: 'Finely diced' },
      { name: 'Carrots & Celery', quantity: 1, unit: 'each', notes: 'Finely diced' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Meat Ragù', instruction: 'Sauté soffritto (onion, carrot, celery). Brown mixed meats. Add wine, reduce. Add tomatoes and simmer 45 minutes.', timerMinutes: 60 },
      { stepNumber: 2, title: 'Prepare Béchamel', instruction: 'Melt butter over medium heat. Whisk in flour and cook 1 minute. Gradually add warm milk, whisking constantly until thick and creamy. Season with nutmeg.', timerMinutes: 12 },
      { stepNumber: 3, title: 'Layer the Lasagna', instruction: 'In a baking dish, alternate layers: béchamel, pasta sheets, ragù, béchamel, Parmigiano. Repeat 4-5 times. Top with final béchamel and generous Parmigiano.', timerMinutes: 10 },
      { stepNumber: 4, title: 'Bake Until Golden', instruction: 'Cover with foil and bake at 375°F (190°C) for 30 minutes. Uncover and bake 15 more minutes until golden and bubbling. Rest 10 minutes before serving.', timerMinutes: 45 },
    ],
  },

  // ─────────────────────────────────────────────
  // INDIAN RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Rich Delhi-Style Butter Chicken (Murgh Makhani)',
    description: 'Tender tandoori-spiced chicken simmered in an aromatic, velvety tomato, butter, and cashew cream gravy infused with dried fenugreek leaves (kasoori methi).',
    cuisine: 'Indian',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    caloriesPerServing: 620,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=a03U45jFxOI',
    isFeatured: true,
    ingredients: [
      { name: 'Boneless Chicken Thighs', quantity: 700, unit: 'g', notes: 'Cut into bite-sized pieces' },
      { name: 'Greek Yogurt', quantity: 0.5, unit: 'cup', notes: 'For marinade' },
      { name: 'Ginger Garlic Paste', quantity: 2, unit: 'tbsp', notes: 'Freshly crushed' },
      { name: 'Kashmiri Red Chilli Powder', quantity: 2, unit: 'tsp', notes: 'For vibrant color' },
      { name: 'Garam Masala', quantity: 1.5, unit: 'tsp', notes: 'Aromatic spice blend' },
      { name: 'Unsalted Butter', quantity: 50, unit: 'g', notes: 'Divided' },
      { name: 'San Marzano Canned Tomatoes', quantity: 500, unit: 'g', notes: 'Pureed smooth' },
      { name: 'Heavy Cream', quantity: 0.5, unit: 'cup', notes: 'Fresh cooking cream' },
      { name: 'Cashew Nuts', quantity: 15, unit: 'pieces', notes: 'Soaked and blended' },
      { name: 'Kasoori Methi (Dried Fenugreek)', quantity: 1, unit: 'tbsp', notes: 'Crushed between palms' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Marinate Chicken', instruction: 'Combine yogurt, ginger-garlic paste, Kashmiri chilli, garam masala, salt, and lemon juice. Coat chicken and rest for 20 minutes.', timerMinutes: 20 },
      { stepNumber: 2, title: 'Sear Chicken', instruction: 'Pan-sear marinated chicken in hot skillet with 1 tbsp butter until lightly charred (about 80% cooked). Set aside.', timerMinutes: 8 },
      { stepNumber: 3, title: 'Simmer the Makhani Sauce', instruction: 'Melt remaining butter. Add pureed tomatoes, cashew paste, Kashmiri chilli, and salt. Simmer until oil separates.', timerMinutes: 12 },
      { stepNumber: 4, title: 'Combine & Finish with Cream', instruction: 'Add seared chicken. Pour in heavy cream and honey. Simmer 5 minutes. Crush kasoori methi over top. Serve with naan and basmati rice.', timerMinutes: 5 },
    ],
  },
  {
    title: 'Punjabi Palak Paneer (Spinach & Cottage Cheese)',
    description: 'Creamy, vibrant spinach sauce packed with aromatic spices, nestled with golden pan-fried Indian cottage cheese cubes — a beloved North Indian vegetarian classic.',
    cuisine: 'Indian',
    mealType: 'Dinner',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    caloriesPerServing: 380,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1645177628172-a8b23b106ec2?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=-rPNmeRkNSE',
    isFeatured: true,
    ingredients: [
      { name: 'Fresh Baby Spinach', quantity: 500, unit: 'g', notes: 'Blanched and pureed' },
      { name: 'Paneer (Indian Cottage Cheese)', quantity: 300, unit: 'g', notes: 'Cut into cubes, lightly fried' },
      { name: 'Yellow Onion', quantity: 1, unit: 'large', notes: 'Finely chopped' },
      { name: 'Ginger Garlic Paste', quantity: 1.5, unit: 'tbsp', notes: 'Fresh' },
      { name: 'Tomatoes', quantity: 2, unit: 'medium', notes: 'Pureed' },
      { name: 'Cumin Seeds', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Coriander Powder', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Garam Masala', quantity: 0.5, unit: 'tsp', notes: '' },
      { name: 'Heavy Cream', quantity: 3, unit: 'tbsp', notes: 'For richness' },
      { name: 'Ghee or Oil', quantity: 2, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Blanch and Puree Spinach', instruction: 'Blanch spinach in boiling water for 2 minutes. Transfer to ice water. Drain and blend to a smooth puree.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Prepare the Base', instruction: 'Heat ghee; fry cumin seeds. Add onions and cook until golden. Add ginger-garlic paste, tomato puree, and all spices. Cook until oil separates.', timerMinutes: 12 },
      { stepNumber: 3, title: 'Add Spinach', instruction: 'Stir in the spinach puree. Season with salt. Simmer 5 minutes. Adjust consistency with a splash of water.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Add Paneer and Cream', instruction: 'Gently fold in fried paneer cubes. Drizzle cream and stir. Serve hot with roti or basmati rice.', timerMinutes: 3 },
    ],
  },
  {
    title: 'Biryani (Hyderabadi Dum Chicken Biryani)',
    description: 'Fragrant long-grain basmati rice layered with marinated saffron chicken, caramelized onions, fresh mint, and slow-cooked using the traditional dum (steam) method.',
    cuisine: 'Indian',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 40,
    cookTime: 50,
    servings: 6,
    caloriesPerServing: 750,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=EiVoWp5b93s',
    isFeatured: true,
    ingredients: [
      { name: 'Basmati Rice', quantity: 3, unit: 'cups', notes: 'Soaked 30 minutes' },
      { name: 'Bone-in Chicken Pieces', quantity: 1, unit: 'kg', notes: 'Marinated' },
      { name: 'Full-Fat Yogurt', quantity: 1, unit: 'cup', notes: 'For marinade' },
      { name: 'Biryani Masala', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Saffron Strands', quantity: 0.25, unit: 'tsp', notes: 'Soaked in warm milk' },
      { name: 'Fried Onions (Birista)', quantity: 1, unit: 'cup', notes: 'Crispy, golden brown' },
      { name: 'Fresh Mint Leaves', quantity: 0.5, unit: 'cup', notes: '' },
      { name: 'Fresh Cilantro', quantity: 0.5, unit: 'cup', notes: '' },
      { name: 'Whole Spices (Cardamom, Cloves, Bay Leaves)', quantity: 1, unit: 'set', notes: 'For rice water' },
      { name: 'Ghee', quantity: 4, unit: 'tbsp', notes: 'Divided' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Marinate Chicken', instruction: 'Combine yogurt, biryani masala, ginger-garlic paste, chilli powder, half the fried onions, mint, and cilantro. Marinate chicken for at least 2 hours.', timerMinutes: 120 },
      { stepNumber: 2, title: 'Parboil Rice', instruction: 'Boil water with whole spices and salt. Add soaked rice and cook exactly 70% done (it should still have a bite). Drain immediately.', timerMinutes: 8 },
      { stepNumber: 3, title: 'Layer the Biryani', instruction: 'In a heavy pot, spread marinated chicken as base. Layer parboiled rice over it. Drizzle saffron milk, ghee, fried onions, mint, and cilantro.', timerMinutes: 8 },
      { stepNumber: 4, title: 'Dum Cook', instruction: 'Seal pot tightly with foil then lid. Cook on high heat for 5 minutes. Reduce to lowest flame and dum cook 25 minutes. Rest 10 minutes before opening.', timerMinutes: 35 },
    ],
  },

  // ─────────────────────────────────────────────
  // MEXICAN RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Baja California Crispy Fish Tacos',
    description: 'Golden beer-battered flaky white fish nestled inside warm corn tortillas, layered with crunchy chipotle slaw, creamy avocado salsa, and fresh lime wedges.',
    cuisine: 'Mexican',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 20,
    cookTime: 12,
    servings: 4,
    caloriesPerServing: 420,
    dietaryTags: ['Pescatarian'],
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=J2O0iYjj3iI',
    isFeatured: true,
    ingredients: [
      { name: 'Fresh Cod or Halibut Fillets', quantity: 500, unit: 'g', notes: 'Cut into 3-inch strips' },
      { name: 'Mexican Cold Beer', quantity: 1, unit: 'cup', notes: 'E.g. Modelo or Corona' },
      { name: 'All-Purpose Flour', quantity: 1, unit: 'cup', notes: 'Plus 3 tbsp for dusting' },
      { name: 'Cornstarch', quantity: 2, unit: 'tbsp', notes: 'For ultra crispiness' },
      { name: 'Shredded Cabbage', quantity: 2, unit: 'cups', notes: 'Thinly sliced' },
      { name: 'Chipotle in Adobo Mayo', quantity: 4, unit: 'tbsp', notes: 'Spicy crema' },
      { name: 'Corn Tortillas', quantity: 8, unit: 'small', notes: 'Warmed on a dry skillet' },
      { name: 'Fresh Limes & Cilantro', quantity: 1, unit: 'bunch', notes: 'For garnish' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Prepare Chipotle Slaw', instruction: 'Toss shredded cabbage with chipotle mayo, fresh lime juice, cilantro, and a pinch of salt. Chill in refrigerator.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Whisk Beer Batter', instruction: 'Whisk flour, cornstarch, baking powder, garlic powder, and salt. Pour in chilled beer and whisk until smooth and bubbly.', timerMinutes: 3 },
      { stepNumber: 3, title: 'Fry the Fish', instruction: 'Heat oil to 375°F. Dust fish strips in dry flour, dip into beer batter, and fry in batches for 3-4 minutes until crisp and golden.', timerMinutes: 4 },
      { stepNumber: 4, title: 'Assemble Tacos', instruction: 'Warm corn tortillas. Lay down crisp fish, top with chipotle slaw, avocado slices, cilantro, and a generous squeeze of lime.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Authentic Mexican Guacamole & Chips',
    description: 'Perfectly chunky, fresh-made guacamole prepared tableside using ripe Hass avocados, white onion, serrano chillies, lime juice, and cilantro — served with house-made tortilla chips.',
    cuisine: 'Mexican',
    mealType: 'Snack',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    caloriesPerServing: 220,
    dietaryTags: ['Vegan', 'Gluten-Free', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=NF2lrDeTU_g',
    isFeatured: false,
    ingredients: [
      { name: 'Ripe Hass Avocados', quantity: 3, unit: 'large', notes: 'Perfectly ripe' },
      { name: 'White Onion', quantity: 0.25, unit: 'medium', notes: 'Very finely diced' },
      { name: 'Serrano or Jalapeño', quantity: 1, unit: 'medium', notes: 'Seeds removed for less heat' },
      { name: 'Fresh Lime Juice', quantity: 2, unit: 'tbsp', notes: 'Freshly squeezed' },
      { name: 'Fresh Cilantro', quantity: 0.25, unit: 'cup', notes: 'Roughly chopped' },
      { name: 'Kosher Salt', quantity: 0.5, unit: 'tsp', notes: '' },
      { name: 'Roma Tomato', quantity: 1, unit: 'small', notes: 'Seeds removed, finely diced' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Prep the Aromatics', instruction: 'Finely dice white onion and serrano. Rinse diced onion in cold water and pat dry to remove bite. Dice tomato, discarding seeds.', timerMinutes: 4 },
      { stepNumber: 2, title: 'Mash Avocados', instruction: 'Halve and pit avocados. Scoop flesh into a mortar or bowl. Mash to your desired consistency — some chunks are great!', timerMinutes: 2 },
      { stepNumber: 3, title: 'Mix & Season', instruction: 'Fold in onion, serrano, cilantro, lime juice, and salt. Taste and adjust. Fold in tomato last to prevent excess liquid.', timerMinutes: 2 },
      { stepNumber: 4, title: 'Serve Fresh', instruction: 'Serve immediately with tortilla chips or warm corn tortillas. Place avocado pit in the bowl to slow browning if storing.', timerMinutes: 1 },
    ],
  },
  {
    title: 'Slow-Cooked Beef Barbacoa Tacos',
    description: 'Incredibly tender, spiced beef slow-cooked with chipotle peppers, lime, and cumin until it falls apart into juicy shreds, perfect for authentic street tacos.',
    cuisine: 'Mexican',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 20,
    cookTime: 240,
    servings: 8,
    caloriesPerServing: 390,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1640719028782-8230f1bdc93f?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=Med7sVDBYJs',
    isFeatured: false,
    ingredients: [
      { name: 'Beef Chuck Roast', quantity: 1.5, unit: 'kg', notes: 'Cut into large chunks' },
      { name: 'Chipotle Peppers in Adobo', quantity: 3, unit: 'pieces', notes: 'With 2 tbsp sauce' },
      { name: 'Beef Broth', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Fresh Lime Juice', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Ground Cumin', quantity: 2, unit: 'tsp', notes: '' },
      { name: 'Dried Oregano', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Garlic Cloves', quantity: 5, unit: 'cloves', notes: 'Minced' },
      { name: 'Corn Tortillas', quantity: 16, unit: 'small', notes: 'For serving' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Blend the Marinade', instruction: 'Blend chipotle peppers, garlic, lime juice, beef broth, cumin, oregano, cloves, and salt until smooth.', timerMinutes: 3 },
      { stepNumber: 2, title: 'Sear the Beef', instruction: 'Season beef chunks generously with salt. Sear in batches in a hot Dutch oven with oil until browned on all sides.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Slow Cook', instruction: 'Pour chipotle sauce over beef in slow cooker or Dutch oven. Add bay leaves. Cook on low for 6-8 hours or at 300°F in oven for 3.5-4 hours.', timerMinutes: 240 },
      { stepNumber: 4, title: 'Shred and Serve', instruction: 'Shred beef using two forks. Return to cooking juices. Serve in doubled corn tortillas with white onion, cilantro, salsa, and lime.', timerMinutes: 5 },
    ],
  },

  // ─────────────────────────────────────────────
  // JAPANESE RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Traditional Tokyo Shoyu Ramen with Chashu',
    description: 'Comforting rich dashi and chicken broth infused with seasoned shoyu tare, chewy noodles, melt-in-your-mouth pork belly chashu, jammy ajitsuke tamago, and nori.',
    cuisine: 'Japanese',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 30,
    cookTime: 45,
    servings: 4,
    caloriesPerServing: 680,
    dietaryTags: [],
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=r3_tcQiyGG8',
    isFeatured: true,
    ingredients: [
      { name: 'Fresh Ramen Noodles', quantity: 4, unit: 'portions', notes: 'Medium-wavy' },
      { name: 'Rolled Pork Belly Chashu', quantity: 400, unit: 'g', notes: 'Braised and sliced' },
      { name: 'Ramen Eggs (Ajitsuke Tamago)', quantity: 4, unit: 'halved', notes: 'Marinated soft-boiled' },
      { name: 'Rich Chicken & Dashi Stock', quantity: 6, unit: 'cups', notes: 'Simmered broth' },
      { name: 'Japanese Soy Sauce (Shoyu)', quantity: 0.5, unit: 'cup', notes: 'For tare' },
      { name: 'Mirin and Sake', quantity: 4, unit: 'tbsp', notes: 'For aroma' },
      { name: 'Bamboo Shoots (Menma)', quantity: 0.5, unit: 'cup', notes: 'Seasoned' },
      { name: 'Scallions', quantity: 3, unit: 'stalks', notes: 'Finely sliced' },
      { name: 'Nori Seaweed Sheets', quantity: 4, unit: 'squares', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Prepare Shoyu Tare and Broth', instruction: 'Simmer soy sauce, mirin, sake, kombu, and garlic for 10 minutes to create concentrated tare. Heat rich stock to near-boiling.', timerMinutes: 10 },
      { stepNumber: 2, title: 'Sear Chashu Slices', instruction: 'Using a kitchen torch or screaming hot cast iron pan, quickly sear chashu slices on both sides to caramelize the braising sugars.', timerMinutes: 3 },
      { stepNumber: 3, title: 'Cook Fresh Noodles', instruction: 'Boil ramen noodles in rolling water for exactly 90 seconds until chewy. Shake out all excess water vigorously.', timerMinutes: 2 },
      { stepNumber: 4, title: 'Assemble Bowls', instruction: 'Ladle 3 tbsp hot tare into each warmed bowl. Pour in 1.5 cups boiling broth. Fold in noodles. Top with chashu, halved egg, menma, sliced scallions, and crisp nori.', timerMinutes: 3 },
    ],
  },
  {
    title: 'Crispy Vegetable Tempura with Dipping Sauce',
    description: 'Light, airy Japanese battered vegetables — shishito peppers, sweet potato, eggplant, and broccoli — fried to shatteringly crisp perfection with a cold dashi-soy dipping sauce.',
    cuisine: 'Japanese',
    mealType: 'Snack',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 320,
    dietaryTags: ['Vegan', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=SN0P1WUK3b4',
    isFeatured: false,
    ingredients: [
      { name: 'Sweet Potato', quantity: 1, unit: 'medium', notes: 'Sliced into 0.5cm rounds' },
      { name: 'Japanese Eggplant', quantity: 1, unit: 'medium', notes: 'Sliced into fans' },
      { name: 'Broccoli Florets', quantity: 1, unit: 'cup', notes: 'Small pieces' },
      { name: 'Shishito Peppers', quantity: 8, unit: 'pieces', notes: '' },
      { name: 'Cake Flour', quantity: 1, unit: 'cup', notes: 'Low-protein flour is key' },
      { name: 'Ice Cold Sparkling Water', quantity: 1, unit: 'cup', notes: 'Very cold!' },
      { name: 'Egg', quantity: 1, unit: 'large', notes: 'Beaten' },
      { name: 'Dashi Stock', quantity: 1, unit: 'cup', notes: 'For dipping sauce' },
      { name: 'Soy Sauce & Mirin', quantity: 3, unit: 'tbsp', notes: 'For dipping sauce' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Dipping Sauce', instruction: 'Combine dashi, soy sauce, and mirin. Bring to a simmer. Remove from heat. Serve warm with grated daikon and ginger.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Mix the Tempura Batter', instruction: 'In a cold bowl, lightly mix ice water, egg, and sifted cake flour with a fork. DO NOT over-mix — lumps are fine and essential for crispiness!', timerMinutes: 2 },
      { stepNumber: 3, title: 'Heat Oil', instruction: 'Heat neutral oil to 340°F (170°C) in a deep heavy pot. Test with a drop of batter — it should sink briefly then rise immediately.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Fry Tempura', instruction: 'Dip vegetables into cold batter and fry in small batches 2-3 minutes until pale golden and crispy. Drain on a rack, never on paper towels.', timerMinutes: 10 },
    ],
  },
  {
    title: 'Japanese Beef Gyudon (Beef Rice Bowl)',
    description: 'Silky, sweet-savory thinly sliced beef and onions simmered in a dashi-soy-mirin sauce, served over steamed white rice topped with a raw egg yolk and pickled ginger.',
    cuisine: 'Japanese',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    caloriesPerServing: 550,
    dietaryTags: [],
    image: 'https://images.unsplash.com/photo-1562802378-063ec186a863?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=osG3R8WWonc',
    isFeatured: false,
    ingredients: [
      { name: 'Thinly Sliced Beef Ribeye', quantity: 300, unit: 'g', notes: 'Paper-thin shabu-shabu style' },
      { name: 'Yellow Onion', quantity: 1, unit: 'large', notes: 'Thinly sliced into half-moons' },
      { name: 'Dashi Stock', quantity: 0.75, unit: 'cup', notes: '' },
      { name: 'Japanese Soy Sauce', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Mirin', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Sugar', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Steamed Japanese Rice', quantity: 2, unit: 'bowls', notes: '' },
      { name: 'Egg Yolks', quantity: 2, unit: 'raw', notes: 'One per bowl' },
      { name: 'Pickled Red Ginger (Beni Shoga)', quantity: 2, unit: 'tbsp', notes: 'For garnish' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Simmer Onions', instruction: 'Bring dashi, soy sauce, mirin, and sugar to a gentle simmer in a wide pan. Add sliced onions. Cook until translucent and tender, about 5 minutes.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Cook the Beef', instruction: 'Scatter thin beef slices over the simmering onions. Cook uncovered on medium heat just until beef is barely pink, about 2-3 minutes. Do not overcook.', timerMinutes: 3 },
      { stepNumber: 3, title: 'Serve Over Rice', instruction: 'Ladle beef and onions generously over steamed rice. Spoon braising liquid over top.', timerMinutes: 1 },
      { stepNumber: 4, title: 'Garnish and Serve', instruction: 'Make a small well in the center and nestle in a raw egg yolk. Top with pickled red ginger and serve immediately with a sprinkle of togarashi.', timerMinutes: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // AMERICAN RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Artisanal Sourdough Avocado Toast with Poached Eggs',
    description: 'Thick-cut toasted artisanal sourdough bread topped with creamy smashed hass avocados, zaatar seasoning, microgreens, and runny poached eggs.',
    cuisine: 'American',
    mealType: 'Breakfast',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    caloriesPerServing: 350,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=GxL9fTvf4go',
    isFeatured: true,
    ingredients: [
      { name: 'Artisan Sourdough Bread', quantity: 2, unit: 'slices', notes: 'Thick cut' },
      { name: 'Ripe Hass Avocados', quantity: 2, unit: 'medium', notes: 'Peeled and seeded' },
      { name: 'Fresh Farm Eggs', quantity: 2, unit: 'large', notes: 'For poaching' },
      { name: 'Extra Virgin Olive Oil', quantity: 1, unit: 'tbsp', notes: 'First cold-pressed' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp', notes: 'Freshly squeezed' },
      { name: 'Chili Flakes & Sea Salt Flakes', quantity: 1, unit: 'tsp', notes: 'Maldon salt' },
      { name: 'Microgreens or Radish Sprouts', quantity: 0.25, unit: 'cup', notes: 'For garnish' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Smash Avocado', instruction: 'Roughly mash avocados with lemon juice, olive oil, salt, and freshly cracked black pepper. Keep slight texture.', timerMinutes: 3 },
      { stepNumber: 2, title: 'Toast the Bread', instruction: 'Brush sourdough with olive oil and toast in a skillet or toaster until deep golden brown and crunchy.', timerMinutes: 4 },
      { stepNumber: 3, title: 'Poach the Eggs', instruction: 'Bring water with a dash of white vinegar to a gentle simmer. Create a gentle whirlpool and slip in cracked egg. Poach for 3 minutes for a perfectly runny yolk.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Assemble and Season', instruction: 'Spread avocado generously over warm toasts. Carefully place poached eggs on top. Sprinkle chili flakes, flaky sea salt, and microgreens.', timerMinutes: 1 },
    ],
  },
  {
    title: 'The Ultimate Smash Burger',
    description: 'Two thin, smashed beef patties with perfectly lacey, crispy edges, stacked with American cheese, caramelized onions, pickles, and special sauce in a toasted brioche bun.',
    cuisine: 'American',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    caloriesPerServing: 780,
    dietaryTags: [],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=0nrRJdFaJjI',
    isFeatured: true,
    ingredients: [
      { name: 'Ground Beef (80/20)', quantity: 400, unit: 'g', notes: 'Loosely formed into 4 balls' },
      { name: 'Brioche Burger Buns', quantity: 2, unit: 'pieces', notes: 'Split and buttered' },
      { name: 'American Cheese Slices', quantity: 4, unit: 'slices', notes: '' },
      { name: 'Yellow Onion', quantity: 1, unit: 'small', notes: 'Very thinly sliced' },
      { name: 'Dill Pickle Slices', quantity: 1, unit: 'handful', notes: '' },
      { name: 'Mayonnaise, Ketchup, Mustard', quantity: 2, unit: 'tbsp', notes: 'For special sauce' },
      { name: 'Unsalted Butter', quantity: 1, unit: 'tbsp', notes: 'For buns' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Special Sauce', instruction: 'Mix mayo, ketchup, yellow mustard, pickled jalapeños, and garlic powder. Set aside.', timerMinutes: 2 },
      { stepNumber: 2, title: 'Smash the Patties', instruction: 'Heat cast iron skillet to ripping hot over high heat. Place beef balls on pan and immediately smash flat with a heavy spatula. Season with salt. Cook 90 seconds until dark sear forms.', timerMinutes: 3 },
      { stepNumber: 3, title: 'Cheese and Stack', instruction: 'Flip patties. Immediately top with cheese slices. Cook 60 seconds. Stack two patties per burger.', timerMinutes: 2 },
      { stepNumber: 4, title: 'Toast and Assemble', instruction: 'Toast buttered buns cut-side down in the same skillet until golden. Spread special sauce on both buns. Add pickles, onions, and stacked patties. Serve immediately.', timerMinutes: 3 },
    ],
  },
  {
    title: 'Blueberry Buttermilk Pancakes',
    description: 'Tall, fluffy, cloud-like pancakes packed with fresh blueberries, made with tangy buttermilk for incredible rise and tenderness, served with maple syrup and whipped butter.',
    cuisine: 'American',
    mealType: 'Breakfast',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 420,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=-fMcKbeqX4g',
    isFeatured: false,
    ingredients: [
      { name: 'All-Purpose Flour', quantity: 2, unit: 'cups', notes: '' },
      { name: 'Full-Fat Buttermilk', quantity: 2, unit: 'cups', notes: '' },
      { name: 'Fresh Blueberries', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Eggs', quantity: 2, unit: 'large', notes: '' },
      { name: 'Baking Powder', quantity: 2, unit: 'tsp', notes: '' },
      { name: 'Baking Soda', quantity: 0.5, unit: 'tsp', notes: '' },
      { name: 'Sugar', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Unsalted Butter', quantity: 3, unit: 'tbsp', notes: 'Melted' },
      { name: 'Pure Maple Syrup', quantity: 4, unit: 'tbsp', notes: 'For serving' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Mix Dry Ingredients', instruction: 'In a large bowl, whisk flour, baking powder, baking soda, sugar, and a pinch of salt.', timerMinutes: 2 },
      { stepNumber: 2, title: 'Combine Wet Ingredients', instruction: 'In another bowl, whisk buttermilk, eggs, and melted butter. Pour over dry ingredients. Mix gently until just combined — lumps are totally fine! Do NOT over-mix.', timerMinutes: 3 },
      { stepNumber: 3, title: 'Cook Pancakes', instruction: 'Heat a lightly buttered non-stick pan over medium heat. Pour 1/3 cup batter. Scatter blueberries on top. Cook until bubbles form and edges look set, about 2 minutes. Flip and cook 1 more minute.', timerMinutes: 12 },
      { stepNumber: 4, title: 'Serve', instruction: 'Stack pancakes high. Serve immediately with whipped salted butter and warm pure maple syrup.', timerMinutes: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // MEDITERRANEAN RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Santorini Greek Salad with Block Feta',
    description: 'A vibrant Mediterranean salad of sun-ripened vine tomatoes, crisp cucumbers, Kalamata olives, red onion, and authentic Greek sheep milk feta drenched in oregano olive oil.',
    cuisine: 'Mediterranean',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 12,
    cookTime: 0,
    servings: 4,
    caloriesPerServing: 240,
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Keto'],
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=oSn0Y9c99NU',
    isFeatured: false,
    ingredients: [
      { name: 'Ripe Vine Tomatoes', quantity: 4, unit: 'large', notes: 'Cut into wedges' },
      { name: 'Persian Cucumbers', quantity: 3, unit: 'medium', notes: 'Thick sliced' },
      { name: 'Red Onion', quantity: 1, unit: 'small', notes: 'Thinly sliced into rings' },
      { name: 'Kalamata Olives', quantity: 0.5, unit: 'cup', notes: 'Pitted' },
      { name: 'Greek Feta Cheese', quantity: 200, unit: 'g', notes: 'Whole block, not crumbled' },
      { name: 'Extra Virgin Olive Oil', quantity: 4, unit: 'tbsp', notes: 'Greek Kalamata oil' },
      { name: 'Dried Wild Oregano', quantity: 1, unit: 'tbsp', notes: 'Aromatic' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Chop Produce', instruction: 'Cut tomatoes into irregular wedges. Slice cucumbers into half-moons. Thinly slice red onion and soak in cold water 5 minutes.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Toss Vegetables', instruction: 'Combine tomatoes, cucumbers, drained onions, and Kalamata olives in a wide shallow bowl. Season with sea salt.', timerMinutes: 2 },
      { stepNumber: 3, title: 'Dress and Crown with Feta', instruction: 'Drizzle generously with olive oil and red wine vinegar. Place the whole feta block right in the center. Crush wild oregano across the entire dish.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Lebanese Lamb Kofta Kebabs with Tzatziki',
    description: 'Perfectly spiced ground lamb and beef kofta kebabs infused with parsley, onion, warm Middle Eastern spices, grilled over charcoal, served with cooling tzatziki and warm pita.',
    cuisine: 'Mediterranean',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 20,
    cookTime: 12,
    servings: 4,
    caloriesPerServing: 480,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=NC5dxtGLqw4',
    isFeatured: true,
    ingredients: [
      { name: 'Ground Lamb', quantity: 500, unit: 'g', notes: '20% fat content' },
      { name: 'Ground Beef', quantity: 250, unit: 'g', notes: '' },
      { name: 'Yellow Onion', quantity: 1, unit: 'medium', notes: 'Grated, liquid squeezed out' },
      { name: 'Fresh Flat-Leaf Parsley', quantity: 0.5, unit: 'cup', notes: 'Finely chopped' },
      { name: 'Ground Cumin & Coriander', quantity: 1.5, unit: 'tsp each', notes: '' },
      { name: 'Allspice and Cinnamon', quantity: 0.5, unit: 'tsp each', notes: '' },
      { name: 'Greek Yogurt', quantity: 1, unit: 'cup', notes: 'For tzatziki' },
      { name: 'Garlic, Cucumber, Dill', quantity: 1, unit: 'set', notes: 'For tzatziki' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Mix the Kofta', instruction: 'Combine ground lamb, beef, grated onion, parsley, cumin, coriander, allspice, cinnamon, salt, and pepper. Mix vigorously until paste-like. Chill 30 minutes.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Make Tzatziki', instruction: 'Grate cucumber, squeeze dry. Mix with yogurt, crushed garlic, chopped dill, olive oil, and lemon juice. Season well. Chill.', timerMinutes: 8 },
      { stepNumber: 3, title: 'Shape Kofta', instruction: 'Divide meat into 8 portions. Wet your hands. Wrap each portion firmly around a metal skewer, shaping into long oval cylinders.', timerMinutes: 8 },
      { stepNumber: 4, title: 'Grill to Perfection', instruction: 'Grill over very hot charcoal or gas grill, turning every 2-3 minutes until charred outside but still juicy inside, about 10-12 minutes total. Serve with pita, tzatziki, and tomato-onion salad.', timerMinutes: 12 },
    ],
  },
  {
    title: 'Creamy Hummus with Spiced Lamb',
    description: 'Silky smooth chickpea hummus made from scratch with tahini, lemon, and roasted garlic, topped with spiced ground lamb, toasted pine nuts, and garnished with paprika olive oil.',
    cuisine: 'Mediterranean',
    mealType: 'Lunch',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 420,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1601933973783-43cf8a7d4c5f?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=e16giQTp0z0',
    isFeatured: false,
    ingredients: [
      { name: 'Dried Chickpeas', quantity: 300, unit: 'g', notes: 'Soaked overnight, cooked until very tender' },
      { name: 'Good Quality Tahini', quantity: 0.5, unit: 'cup', notes: '' },
      { name: 'Fresh Lemon Juice', quantity: 4, unit: 'tbsp', notes: '' },
      { name: 'Roasted Garlic Cloves', quantity: 4, unit: 'cloves', notes: '' },
      { name: 'Ice Cold Water', quantity: 4, unit: 'tbsp', notes: 'For blending' },
      { name: 'Ground Lamb', quantity: 300, unit: 'g', notes: 'For topping' },
      { name: 'Warm Spices (Allspice, Cinnamon, Cumin)', quantity: 1, unit: 'tsp each', notes: '' },
      { name: 'Pine Nuts', quantity: 3, unit: 'tbsp', notes: 'Toasted golden' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Silky Hummus', instruction: 'Blend very hot cooked chickpeas with tahini, lemon, garlic, and ice water. Blend for 4-5 minutes until incredibly smooth and airy.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Cook Spiced Lamb', instruction: 'Fry ground lamb until crispy and golden. Season with allspice, cinnamon, cumin, and salt. Deglaze pan and cook until fragrant.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Toast Pine Nuts', instruction: 'Toast pine nuts in a dry pan over medium heat until golden, about 2-3 minutes. Watch carefully — they burn quickly!', timerMinutes: 3 },
      { stepNumber: 4, title: 'Plate and Garnish', instruction: 'Swirl hummus onto a wide, shallow plate creating a well in the center. Spoon spiced lamb into the well. Scatter toasted pine nuts. Drizzle with paprika-infused olive oil.', timerMinutes: 2 },
    ],
  },

  // ─────────────────────────────────────────────
  // THAI RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Thai Coconut Green Curry with Jasmine Rice',
    description: 'Fragrant and silky Thai green curry simmered with tender chicken breast, Thai eggplants, bamboo shoots, and fresh sweet Thai basil leaves.',
    cuisine: 'Thai',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    caloriesPerServing: 520,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=XZQ63hG1IjI',
    isFeatured: true,
    ingredients: [
      { name: 'Chicken Breast', quantity: 500, unit: 'g', notes: 'Thinly sliced' },
      { name: 'Thai Green Curry Paste', quantity: 3, unit: 'tbsp', notes: 'Authentic Mae Ploy or Aroy-D' },
      { name: 'Full-Fat Coconut Milk', quantity: 400, unit: 'ml', notes: 'Divided' },
      { name: 'Thai Round Eggplants', quantity: 4, unit: 'pieces', notes: 'Quartered' },
      { name: 'Fish Sauce', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Palm Sugar', quantity: 1, unit: 'tbsp', notes: 'Finely shaved' },
      { name: 'Makrut Lime Leaves', quantity: 4, unit: 'leaves', notes: 'Torn to release oils' },
      { name: 'Fresh Thai Basil Leaves', quantity: 1, unit: 'cup', notes: 'Stirred in at the very end' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Crack the Coconut Milk', instruction: 'Heat 1/2 cup thick coconut cream in a wok over medium heat until coconut oil separates and bubbles.', timerMinutes: 4 },
      { stepNumber: 2, title: 'Fry the Curry Paste', instruction: 'Add green curry paste to hot coconut cream. Fry vigorously for 2 minutes until intensely fragrant and glistening.', timerMinutes: 2 },
      { stepNumber: 3, title: 'Simmer Chicken and Vegetables', instruction: 'Add chicken and stir-fry 3 minutes. Pour in remaining coconut milk, torn lime leaves, palm sugar, and fish sauce. Add eggplants and bamboo shoots. Simmer 10 minutes.', timerMinutes: 10 },
      { stepNumber: 4, title: 'Finish with Basil', instruction: 'Turn off heat. Immediately fold in Thai basil leaves until just wilted. Serve hot with fragrant jasmine rice.', timerMinutes: 1 },
    ],
  },
  {
    title: 'Thai Pad Thai with Tofu & Peanuts',
    description: 'The definitive Thai street food noodle dish — chewy rice noodles stir-fried in tangy tamarind-fish sauce with crispy tofu, fresh bean sprouts, chives, and crushed peanuts.',
    cuisine: 'Thai',
    mealType: 'Lunch',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    caloriesPerServing: 520,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=w2xQMFfB0Jo',
    isFeatured: true,
    ingredients: [
      { name: 'Dried Rice Noodles (3mm)', quantity: 200, unit: 'g', notes: 'Soaked in cold water 30 minutes' },
      { name: 'Extra-Firm Tofu', quantity: 200, unit: 'g', notes: 'Pressed, cubed, and fried crispy' },
      { name: 'Eggs', quantity: 2, unit: 'large', notes: '' },
      { name: 'Tamarind Paste', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Fish Sauce or Soy Sauce', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Palm Sugar or Brown Sugar', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Fresh Bean Sprouts', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Garlic Chives or Green Onions', quantity: 0.5, unit: 'cup', notes: '' },
      { name: 'Crushed Roasted Peanuts', quantity: 4, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Pad Thai Sauce', instruction: 'Combine tamarind paste, fish sauce, palm sugar, and a pinch of chili flakes. Heat until sugar dissolves. Taste — should be sweet, sour, and savory.', timerMinutes: 3 },
      { stepNumber: 2, title: 'Fry Tofu and Aromatics', instruction: 'Heat wok to very high heat with oil. Fry garlic and shallots. Add pressed, cubed tofu and fry until golden-crispy on all sides.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Noodles and Eggs', instruction: 'Add drained rice noodles and all the sauce. Toss rapidly. Push to side of wok. Crack eggs into empty space and scramble until just set. Fold into noodles.', timerMinutes: 4 },
      { stepNumber: 4, title: 'Garnish and Serve', instruction: 'Toss in bean sprouts and garlic chives. Serve with crushed peanuts, dried chili flakes, fresh lime, and extra fish sauce on the side.', timerMinutes: 1 },
    ],
  },
  {
    title: 'Thai Larb Gai (Spicy Minced Chicken Salad)',
    description: 'A vibrant, intensely flavored Thai ground chicken salad with toasted rice powder, fresh herbs, fish sauce, lime, and lots of bird eye chilies — the dish of Thai champions.',
    cuisine: 'Thai',
    mealType: 'Lunch',
    difficulty: 'Easy',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    caloriesPerServing: 320,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=m3SxEEQlzGU',
    isFeatured: false,
    ingredients: [
      { name: 'Ground Chicken', quantity: 300, unit: 'g', notes: '' },
      { name: 'Glutinous Rice', quantity: 2, unit: 'tbsp', notes: 'Dry-toasted until golden, then ground' },
      { name: 'Shallots', quantity: 3, unit: 'pieces', notes: 'Thinly sliced' },
      { name: 'Fresh Mint Leaves', quantity: 0.5, unit: 'cup', notes: 'Whole' },
      { name: 'Fresh Cilantro', quantity: 0.25, unit: 'cup', notes: 'Roughly chopped' },
      { name: 'Bird Eye Chilies', quantity: 3, unit: 'pieces', notes: 'Thinly sliced' },
      { name: 'Fish Sauce', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Fresh Lime Juice', quantity: 4, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Toasted Rice Powder', instruction: 'Dry toast glutinous rice in a pan over medium heat, stirring constantly until golden-amber and nutty. Grind to a coarse powder in a spice grinder.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Cook Ground Chicken', instruction: 'Cook ground chicken in a pan over medium heat with a splash of water. Break up all clumps and cook until just done. Remove from heat immediately.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Dress the Larb', instruction: 'While chicken is still warm, add fish sauce, lime juice, sliced chilies, and shallots. Mix well. Adjust balance of fish sauce and lime to taste.', timerMinutes: 2 },
      { stepNumber: 4, title: 'Add Fresh Herbs and Serve', instruction: 'Fold in fresh mint and cilantro. Sprinkle generous amount of toasted rice powder. Serve with sticky rice and raw vegetables on the side.', timerMinutes: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // FRENCH RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Classic French Vanilla Bean Crème Brûlée',
    description: 'An iconic French dessert with a luxuriously rich, silky smooth vanilla bean custard base hidden beneath a paper-thin, crackly sheet of caramelized amber sugar.',
    cuisine: 'French',
    mealType: 'Dessert',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 15,
    cookTime: 40,
    servings: 6,
    caloriesPerServing: 380,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=vUfuLXqjkHU',
    isFeatured: false,
    ingredients: [
      { name: 'Heavy Whipping Cream', quantity: 2, unit: 'cups', notes: '36% fat' },
      { name: 'Madagascar Vanilla Bean', quantity: 1, unit: 'pod', notes: 'Split and seeds scraped' },
      { name: 'Egg Yolks', quantity: 5, unit: 'large', notes: 'Room temperature' },
      { name: 'Granulated White Sugar', quantity: 0.5, unit: 'cup', notes: 'For custard base' },
      { name: 'Superfine Sugar for Torching', quantity: 6, unit: 'tsp', notes: '1 tsp per ramekin' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Infuse Heavy Cream', instruction: 'Heat heavy cream, scraped vanilla bean seeds, and pod until steaming. Remove from heat and steep for 15 minutes.', timerMinutes: 15 },
      { stepNumber: 2, title: 'Whisk Yolks and Temper', instruction: 'Whisk egg yolks and sugar until pale. Slowly pour warm cream into yolk mixture while constantly whisking to prevent curdling.', timerMinutes: 4 },
      { stepNumber: 3, title: 'Bake in Water Bath', instruction: 'Pour custard through a fine-mesh sieve into 6 ramekins. Place in a baking dish and fill with boiling water halfway up ramekin sides. Bake at 325°F (165°C) for 35 minutes.', timerMinutes: 35 },
      { stepNumber: 4, title: 'Caramelize Crust', instruction: 'Sprinkle superfine sugar evenly across chilled custard. Torch evenly with a culinary torch until amber and bubbly. Let harden for 2 minutes and tap with a spoon!', timerMinutes: 2 },
    ],
  },
  {
    title: 'French Coq au Vin (Wine-Braised Chicken)',
    description: 'A slow-braised French country classic featuring chicken pieces simmered in Burgundy red wine with lardons, pearl onions, mushrooms, and aromatic thyme until meltingly tender.',
    cuisine: 'French',
    mealType: 'Dinner',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 25,
    cookTime: 75,
    servings: 4,
    caloriesPerServing: 640,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=hJswLfXL_GA',
    isFeatured: false,
    ingredients: [
      { name: 'Whole Chicken, Cut into Pieces', quantity: 1.5, unit: 'kg', notes: '' },
      { name: 'Burgundy Red Wine', quantity: 750, unit: 'ml', notes: 'One whole bottle' },
      { name: 'Lardons or Bacon', quantity: 150, unit: 'g', notes: 'Cut into matchsticks' },
      { name: 'Pearl Onions', quantity: 1, unit: 'cup', notes: 'Peeled' },
      { name: 'Button Mushrooms', quantity: 250, unit: 'g', notes: 'Halved' },
      { name: 'Chicken Stock', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Tomato Paste', quantity: 1, unit: 'tbsp', notes: '' },
      { name: 'Fresh Thyme & Bay Leaves', quantity: 1, unit: 'bouquet', notes: 'Tied together' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Marinate Chicken', instruction: 'Place chicken in wine with thyme, bay leaf, and carrot. Marinate overnight in fridge for deepest flavor (optional but recommended).', timerMinutes: 30 },
      { stepNumber: 2, title: 'Brown Lardons and Chicken', instruction: 'Fry lardons until crispy. Remove. Pat dry marinated chicken and brown in batches in the same pot until deep golden. Remove.', timerMinutes: 20 },
      { stepNumber: 3, title: 'Build the Braise', instruction: 'Fry onions and mushrooms. Add tomato paste. Pour in marinade wine and stock. Return chicken and lardons. Bring to boil, cover, and simmer on lowest heat 45 minutes.', timerMinutes: 60 },
      { stepNumber: 4, title: 'Reduce and Finish', instruction: 'Remove chicken. Reduce sauce by half over high heat until glossy and sauce-like. Return chicken and heat through. Serve with crusty bread or mashed potatoes.', timerMinutes: 15 },
    ],
  },

  // ─────────────────────────────────────────────
  // CHINESE RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Cantonese Dim Sum Har Gow (Shrimp Dumplings)',
    description: 'Translucent, delicate hand-folded shrimp dumplings with a crystal-clear steamed skin encasing a juicy prawn, bamboo shoot, and sesame filling — the hallmark of a great dim sum.',
    cuisine: 'Chinese',
    mealType: 'Lunch',
    difficulty: 'Hard',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 45,
    cookTime: 8,
    servings: 4,
    caloriesPerServing: 280,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=YUeI6MtxYCw',
    isFeatured: false,
    ingredients: [
      { name: 'Fresh Tiger Prawns', quantity: 400, unit: 'g', notes: 'Deveined, roughly chopped + some left whole' },
      { name: 'Wheat Starch (Dang Mian)', quantity: 1, unit: 'cup', notes: 'Not regular flour!' },
      { name: 'Tapioca Starch', quantity: 0.25, unit: 'cup', notes: '' },
      { name: 'Boiling Water', quantity: 0.75, unit: 'cup', notes: '' },
      { name: 'Bamboo Shoots', quantity: 0.25, unit: 'cup', notes: 'Finely diced' },
      { name: 'Sesame Oil', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Oyster Sauce', quantity: 1, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make Crystal Dough', instruction: 'Mix wheat starch and tapioca starch. Pour boiling water in one stream while mixing with a fork. Knead while hot until smooth. Rest covered 10 minutes.', timerMinutes: 15 },
      { stepNumber: 2, title: 'Prepare Shrimp Filling', instruction: 'Season chopped prawns with salt, sesame oil, oyster sauce, and white pepper. Mix in bamboo shoots. Chill.', timerMinutes: 8 },
      { stepNumber: 3, title: 'Wrap Dumplings', instruction: 'Roll small pieces of dough into thin circles. Place filling in center. Fold and pleat 7-10 pleats along one side, sealing tightly.', timerMinutes: 25 },
      { stepNumber: 4, title: 'Steam Until Translucent', instruction: 'Line bamboo steamer with parchment. Steam har gow over boiling water for exactly 7-8 minutes until translucent and filling is cooked. Serve immediately with soy sauce.', timerMinutes: 8 },
    ],
  },
  {
    title: 'Mapo Tofu (Sichuan Spicy Braised Tofu)',
    description: 'A fiery, numbing Sichuan classic of silken tofu cubes and ground pork braised in an intensely aromatic, oily sauce of black bean paste, doubanjiang, and tingling Sichuan peppercorns.',
    cuisine: 'Chinese',
    mealType: 'Dinner',
    difficulty: 'Medium',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 380,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=j_jQUz6aOkg',
    isFeatured: true,
    ingredients: [
      { name: 'Silken Tofu', quantity: 500, unit: 'g', notes: 'Cut into 1.5-inch cubes' },
      { name: 'Ground Pork', quantity: 150, unit: 'g', notes: '' },
      { name: 'Doubanjiang (Spicy Bean Paste)', quantity: 2, unit: 'tbsp', notes: 'The soul of the dish' },
      { name: 'Fermented Black Beans', quantity: 1, unit: 'tbsp', notes: 'Rough chopped' },
      { name: 'Sichuan Peppercorns', quantity: 1, unit: 'tsp', notes: 'Toasted and ground' },
      { name: 'Chicken Stock', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Garlic and Ginger', quantity: 3, unit: 'cloves/slices', notes: 'Minced' },
      { name: 'Scallions', quantity: 3, unit: 'stalks', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Fry the Aromatics and Pork', instruction: 'Fry ground pork in a hot wok until browned. Add doubanjiang and black bean paste. Fry 2 minutes until oil turns bright red. Add garlic and ginger.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Add Stock and Tofu', instruction: 'Pour in chicken stock. Bring to boil. Gently slide in tofu cubes. Simmer 5 minutes, occasionally swirling the pan gently (don\'t stir to avoid breaking tofu).', timerMinutes: 5 },
      { stepNumber: 3, title: 'Thicken the Sauce', instruction: 'Mix 1 tbsp cornstarch with 2 tbsp water. Drizzle slowly while swirling to thicken. Add half of ground Sichuan pepper. Bring to final boil.', timerMinutes: 2 },
      { stepNumber: 4, title: 'Finish and Plate', instruction: 'Pour into a bowl. Top with remaining ground Sichuan peppercorns, sliced scallions, and drizzle of chili oil. Serve with steamed white rice.', timerMinutes: 1 },
    ],
  },
  {
    title: 'Classic Stir-Fried Bok Choy with Garlic',
    description: 'A simple, vibrant Chinese restaurant staple — crisp baby bok choy stir-fried in seconds over blazing wok heat with fragrant garlic, oyster sauce, and sesame oil.',
    cuisine: 'Chinese',
    mealType: 'Dinner',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 5,
    cookTime: 5,
    servings: 4,
    caloriesPerServing: 120,
    dietaryTags: ['Vegan', 'Gluten-Free', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=R4cDJVFWDSk',
    isFeatured: false,
    ingredients: [
      { name: 'Baby Bok Choy', quantity: 600, unit: 'g', notes: 'Halved lengthwise' },
      { name: 'Garlic Cloves', quantity: 6, unit: 'cloves', notes: 'Thinly sliced' },
      { name: 'Oyster Sauce or Vegetarian Oyster Sauce', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Sesame Oil', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Neutral Oil', quantity: 2, unit: 'tbsp', notes: 'High smoke point' },
      { name: 'Chicken or Vegetable Stock', quantity: 3, unit: 'tbsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Prepare Bok Choy', instruction: 'Trim the bottom of each bok choy and halve lengthwise. Rinse thoroughly and pat dry.', timerMinutes: 3 },
      { stepNumber: 2, title: 'Heat the Wok', instruction: 'Heat wok over the absolute maximum heat your burner can produce. Add oil and let it smoke slightly — this is essential for wok hei.', timerMinutes: 2 },
      { stepNumber: 3, title: 'Stir-Fry with Garlic', instruction: 'Add garlic first, fry for 15 seconds. Add bok choy cut-side down. Stir-fry rapidly for 2 minutes, tossing constantly.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Sauce and Serve', instruction: 'Drizzle oyster sauce and stock. Toss for 30 more seconds. Finish with sesame oil. Plate immediately and serve with rice.', timerMinutes: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // KOREAN RECIPES
  // ─────────────────────────────────────────────
  {
    title: 'Korean Beef Bulgogi (Marinated BBQ Beef)',
    description: 'Thinly sliced marinated beef in a sweet-savory sauce of soy, pear, sesame, and ginger, grilled over high heat until caramelized and served with lettuce wraps and rice.',
    cuisine: 'Korean',
    mealType: 'Dinner',
    difficulty: 'Easy',
    foodType: 'Non-Veg',
    isVeg: false,
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    caloriesPerServing: 480,
    dietaryTags: ['Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=6ZPfR3S9Rw8',
    isFeatured: true,
    ingredients: [
      { name: 'Beef Ribeye or Sirloin', quantity: 500, unit: 'g', notes: 'Shaved paper-thin' },
      { name: 'Asian Pear', quantity: 0.5, unit: 'small', notes: 'Grated — tenderizes the meat' },
      { name: 'Japanese Soy Sauce', quantity: 3, unit: 'tbsp', notes: '' },
      { name: 'Sesame Oil', quantity: 2, unit: 'tbsp', notes: '' },
      { name: 'Brown Sugar', quantity: 1, unit: 'tbsp', notes: '' },
      { name: 'Garlic', quantity: 4, unit: 'cloves', notes: 'Minced' },
      { name: 'Fresh Ginger', quantity: 1, unit: 'tsp', notes: 'Grated' },
      { name: 'Sesame Seeds & Green Onions', quantity: 2, unit: 'tbsp', notes: 'For garnish' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make the Bulgogi Marinade', instruction: 'Combine grated pear, soy sauce, sesame oil, brown sugar, garlic, ginger, and black pepper. Mix well until sugar dissolves.', timerMinutes: 5 },
      { stepNumber: 2, title: 'Marinate the Beef', instruction: 'Toss shaved beef in marinade. Separate slices. Marinate at least 30 minutes or up to 4 hours in the refrigerator.', timerMinutes: 30 },
      { stepNumber: 3, title: 'Cook on High Heat', instruction: 'Heat a grill or cast iron skillet to very high heat. Cook marinated beef in a single layer without moving for 1-2 minutes. Flip and cook 30 more seconds.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Serve Korean Style', instruction: 'Garnish with sesame seeds and green onions. Serve with steamed rice and wrap in crisp lettuce leaves with sliced garlic, ssamjang paste, and kimchi.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Vegetarian Bibimbap (Korean Mixed Rice Bowl)',
    description: 'A stunning Korean rice bowl topped with individually seasoned and sautéed seasonal vegetables, crispy fried egg, nori, and the legendary gochujang bibimbap sauce.',
    cuisine: 'Korean',
    mealType: 'Lunch',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 25,
    cookTime: 20,
    servings: 2,
    caloriesPerServing: 560,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=jg0CFQoHjio',
    isFeatured: true,
    ingredients: [
      { name: 'Short-Grain White Rice', quantity: 1.5, unit: 'cups', notes: 'Cooked and warm' },
      { name: 'Zucchini', quantity: 1, unit: 'medium', notes: 'Julienned' },
      { name: 'Carrots', quantity: 1, unit: 'medium', notes: 'Julienned' },
      { name: 'Fresh Spinach', quantity: 2, unit: 'cups', notes: 'Blanched' },
      { name: 'Shiitake Mushrooms', quantity: 6, unit: 'pieces', notes: 'Sliced and seasoned' },
      { name: 'Bean Sprouts', quantity: 1, unit: 'cup', notes: 'Blanched and seasoned' },
      { name: 'Gochujang (Korean Chili Paste)', quantity: 2, unit: 'tbsp', notes: 'For the sauce' },
      { name: 'Eggs', quantity: 2, unit: 'large', notes: 'Fried sunny side up' },
      { name: 'Sesame Oil', quantity: 2, unit: 'tsp', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Prepare and Season Vegetables', instruction: 'Blanch spinach and bean sprouts. Season each individually with sesame oil, garlic, and salt. Sauté zucchini, carrots, and mushrooms separately with sesame oil.', timerMinutes: 20 },
      { stepNumber: 2, title: 'Make Gochujang Sauce', instruction: 'Whisk gochujang with sesame oil, soy sauce, honey, garlic, and a splash of rice vinegar until smooth.', timerMinutes: 2 },
      { stepNumber: 3, title: 'Fry the Eggs', instruction: 'Fry eggs in a lightly oiled non-stick pan until whites are set but yolks are still runny. Season with salt.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Assemble and Mix', instruction: 'Add warm rice to a bowl. Arrange each vegetable in a fan pattern over rice. Place fried egg in the center. Drizzle gochujang sauce. Mix vigorously to eat!', timerMinutes: 3 },
    ],
  },

  // ─────────────────────────────────────────────
  // BREAKFAST SPECIALS
  // ─────────────────────────────────────────────
  {
    title: 'Shakshuka (Middle Eastern Eggs in Tomato Sauce)',
    description: 'Perfectly poached eggs nestled in a deeply spiced, vibrant tomato, pepper, and cumin sauce enriched with feta cheese and fresh herbs — a one-pan Middle Eastern breakfast icon.',
    cuisine: 'Mediterranean',
    mealType: 'Breakfast',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    caloriesPerServing: 320,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=Nf0EUTtjkFA',
    isFeatured: false,
    ingredients: [
      { name: 'Eggs', quantity: 4, unit: 'large', notes: '' },
      { name: 'Canned Crushed Tomatoes', quantity: 400, unit: 'g', notes: '' },
      { name: 'Red Bell Pepper', quantity: 1, unit: 'medium', notes: 'Diced' },
      { name: 'Yellow Onion', quantity: 1, unit: 'medium', notes: 'Diced' },
      { name: 'Garlic', quantity: 4, unit: 'cloves', notes: 'Minced' },
      { name: 'Ground Cumin', quantity: 1.5, unit: 'tsp', notes: '' },
      { name: 'Smoked Paprika', quantity: 1, unit: 'tsp', notes: '' },
      { name: 'Crumbled Feta Cheese', quantity: 80, unit: 'g', notes: '' },
      { name: 'Fresh Parsley or Cilantro', quantity: 0.25, unit: 'cup', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Build the Sauce', instruction: 'Sauté onion and pepper in olive oil until soft, about 7 minutes. Add garlic, cumin, paprika, and chili flakes. Cook 1 minute.', timerMinutes: 8 },
      { stepNumber: 2, title: 'Simmer Tomatoes', instruction: 'Add crushed tomatoes. Season generously with salt and pepper. Simmer 8-10 minutes until sauce thickens and deepens in color.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Poach the Eggs', instruction: 'Create 4 wells in the sauce with the back of a spoon. Crack one egg into each well. Cover with a lid and cook on medium-low until whites are just set, about 5-7 minutes.', timerMinutes: 7 },
      { stepNumber: 4, title: 'Garnish and Serve', instruction: 'Remove from heat. Scatter crumbled feta and fresh herbs. Drizzle with extra virgin olive oil. Serve directly from the pan with warm crusty bread.', timerMinutes: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // DESSERTS
  // ─────────────────────────────────────────────
  {
    title: 'No-Bake New York Style Strawberry Cheesecake',
    description: 'A rich, creamy no-bake New York cheesecake on a buttery graham cracker crust, topped with a glossy, jewel-like fresh strawberry compote sauce. Set overnight for best results.',
    cuisine: 'American',
    mealType: 'Dessert',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    caloriesPerServing: 520,
    dietaryTags: ['Vegetarian'],
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=RScfTwEsWWA',
    isFeatured: true,
    ingredients: [
      { name: 'Graham Crackers', quantity: 250, unit: 'g', notes: 'Finely crushed' },
      { name: 'Unsalted Butter', quantity: 100, unit: 'g', notes: 'Melted' },
      { name: 'Full-Fat Cream Cheese', quantity: 800, unit: 'g', notes: 'Room temperature' },
      { name: 'Powdered Sugar', quantity: 1, unit: 'cup', notes: 'Sifted' },
      { name: 'Fresh Lemon Juice & Zest', quantity: 1, unit: 'lemon', notes: '' },
      { name: 'Heavy Whipping Cream', quantity: 1, unit: 'cup', notes: 'Cold, whipped to stiff peaks' },
      { name: 'Fresh Strawberries', quantity: 400, unit: 'g', notes: 'For compote topping' },
      { name: 'Sugar', quantity: 3, unit: 'tbsp', notes: 'For compote' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Make the Crust', instruction: 'Combine crushed graham crackers with melted butter until it resembles wet sand. Press firmly into the bottom of a 9-inch springform pan. Chill for 20 minutes.', timerMinutes: 25 },
      { stepNumber: 2, title: 'Prepare Cheesecake Filling', instruction: 'Beat cream cheese until smooth. Add powdered sugar, vanilla, lemon zest, and lemon juice. Beat until fluffy. Fold in cold whipped cream until just combined.', timerMinutes: 10 },
      { stepNumber: 3, title: 'Set the Cheesecake', instruction: 'Pour filling over chilled crust. Smooth the top. Cover and refrigerate for at least 6 hours, preferably overnight.', timerMinutes: 5 },
      { stepNumber: 4, title: 'Make Strawberry Compote & Serve', instruction: 'Simmer sliced strawberries with sugar and lemon juice for 5 minutes. Cool completely. Pour over set cheesecake just before serving. Unmold and slice.', timerMinutes: 8 },
    ],
  },
  {
    title: 'Mango Kulfi (Indian Frozen Dessert)',
    description: 'Dense, rich, and intensely flavored Indian frozen dessert made from slow-reduced full-fat milk, fresh Alphonso mango pulp, and cardamom — the tropical summer treat of India.',
    cuisine: 'Indian',
    mealType: 'Dessert',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    caloriesPerServing: 290,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1557805931-a67d35ad2af3?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=VMUUVxrxKUE',
    isFeatured: false,
    ingredients: [
      { name: 'Full-Fat Whole Milk', quantity: 1, unit: 'liter', notes: '' },
      { name: 'Sweetened Condensed Milk', quantity: 4, unit: 'tbsp', notes: '' },
      { name: 'Fresh Alphonso Mango Pulp', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Heavy Cream', quantity: 0.25, unit: 'cup', notes: '' },
      { name: 'Ground Cardamom', quantity: 0.5, unit: 'tsp', notes: '' },
      { name: 'Saffron Strands', quantity: 0.25, unit: 'tsp', notes: 'Soaked in warm milk' },
      { name: 'Pistachios', quantity: 3, unit: 'tbsp', notes: 'Chopped, for garnish' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Reduce the Milk', instruction: 'Bring milk to a boil in a heavy-bottomed pot, then reduce to a gentle simmer. Stir frequently and cook until reduced to about 40% of original volume, about 25 minutes.', timerMinutes: 30 },
      { stepNumber: 2, title: 'Add Sweeteners and Flavor', instruction: 'Stir in condensed milk, cardamom, and saffron milk. Cook 5 more minutes. Remove from heat and cool completely.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Mix in Mango and Cream', instruction: 'Blend reduced milk, mango pulp, and heavy cream. Blend until completely smooth and well combined.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Freeze Kulfi', instruction: 'Pour into kulfi molds or ramekins. Insert popsicle sticks. Freeze for at least 6 hours until completely solid. Unmold by running under warm water. Garnish with crushed pistachios.', timerMinutes: 5 },
    ],
  },

  // ─────────────────────────────────────────────
  // BEVERAGES
  // ─────────────────────────────────────────────
  {
    title: 'Authentic South Indian Filter Coffee',
    description: 'The legendary South Indian filter coffee (Kaapi) — strong decoction of dark-roasted chicory coffee, mixed with frothy scalded whole milk, served with spectacular davara glass tumbler pouring.',
    cuisine: 'Indian',
    mealType: 'Beverages',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    caloriesPerServing: 120,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=iJKnyvYnCm4',
    isFeatured: false,
    ingredients: [
      { name: 'South Indian Filter Coffee Powder (80% Coffee, 20% Chicory)', quantity: 4, unit: 'tbsp', notes: '' },
      { name: 'Boiling Water', quantity: 0.5, unit: 'cup', notes: 'For brewing decoction' },
      { name: 'Full-Fat Whole Milk', quantity: 1.5, unit: 'cups', notes: '' },
      { name: 'Sugar', quantity: 2, unit: 'tsp', notes: 'To taste' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Brew the Coffee Decoction', instruction: 'Add coffee powder to the upper filter. Pour boiling water over slowly and let drip completely, about 5-10 minutes. The resulting decoction should be very thick and dark.', timerMinutes: 10 },
      { stepNumber: 2, title: 'Heat and Froth the Milk', instruction: 'Heat whole milk in a pan until nearly boiling. Whisk or froth the milk vigorously.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Combine in the Tumbler', instruction: 'Add 2-3 tbsp of strong coffee decoction to the davara (saucer). Add hot milk and sugar. Stir.', timerMinutes: 1 },
      { stepNumber: 4, title: 'Froth by Pouring', instruction: 'Pour the coffee mixture back and forth between the tumbler and davara from a height at least 5-6 times to create a beautiful froth and perfect temperature. Serve immediately.', timerMinutes: 2 },
    ],
  },
  {
    title: 'Classic Homemade Masala Chai',
    description: 'A warming, aromatic spiced Indian tea made with whole spices — cardamom, ginger, cloves, cinnamon — simmered with a rich blend of black tea and full-fat milk.',
    cuisine: 'Indian',
    mealType: 'Beverages',
    difficulty: 'Easy',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    caloriesPerServing: 90,
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=D8s_0jfo9Yw',
    isFeatured: false,
    ingredients: [
      { name: 'Water', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Full-Fat Whole Milk', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Assam or CTC Black Tea Leaves', quantity: 2, unit: 'tsp', notes: 'Strong black tea' },
      { name: 'Sugar', quantity: 2, unit: 'tsp', notes: 'Or more to taste' },
      { name: 'Green Cardamom Pods', quantity: 4, unit: 'pods', notes: 'Lightly crushed' },
      { name: 'Fresh Ginger', quantity: 1, unit: 'inch', notes: 'Grated or sliced' },
      { name: 'Whole Cloves', quantity: 2, unit: 'pieces', notes: '' },
      { name: 'Cinnamon Stick', quantity: 0.5, unit: 'stick', notes: '' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Crush the Spices', instruction: 'Lightly crush cardamom pods, cloves, and cinnamon. Grate fresh ginger.', timerMinutes: 2 },
      { stepNumber: 2, title: 'Simmer the Spiced Water', instruction: 'Bring water to a boil with all the crushed spices and ginger. Simmer for 2 minutes to release flavors.', timerMinutes: 4 },
      { stepNumber: 3, title: 'Add Tea and Milk', instruction: 'Add tea leaves to the boiling water. Pour in milk and add sugar. Bring back to a vigorous boil, then reduce to medium-high.', timerMinutes: 3 },
      { stepNumber: 4, title: 'Froth and Strain', instruction: 'Let the chai rise to a boil 2-3 times, stirring vigorously each time for froth. Strain through a fine sieve into cups. Serve piping hot.', timerMinutes: 2 },
    ],
  },

  // ─────────────────────────────────────────────
  // ADDITIONAL SNACKS
  // ─────────────────────────────────────────────
  {
    title: 'Crispy Falafel with Tahini Sauce',
    description: 'Deeply golden, wonderfully crispy outside and vivid green inside, these authentic chickpea and herb falafel balls are fried to perfection and served with creamy tahini sauce and pita.',
    cuisine: 'Mediterranean',
    mealType: 'Snack',
    difficulty: 'Medium',
    foodType: 'Veg',
    isVeg: true,
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    caloriesPerServing: 380,
    dietaryTags: ['Vegan', 'Gluten-Free', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1529543544282-ea669407fca3?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=0HtyesvxjqY',
    isFeatured: false,
    ingredients: [
      { name: 'Dried Chickpeas', quantity: 250, unit: 'g', notes: 'Soaked 24 hours — NEVER use canned!' },
      { name: 'Fresh Parsley', quantity: 1, unit: 'cup', notes: '' },
      { name: 'Fresh Cilantro', quantity: 0.5, unit: 'cup', notes: '' },
      { name: 'Yellow Onion', quantity: 0.5, unit: 'medium', notes: 'Roughly chopped' },
      { name: 'Garlic Cloves', quantity: 4, unit: 'cloves', notes: '' },
      { name: 'Ground Cumin & Coriander', quantity: 1.5, unit: 'tsp each', notes: '' },
      { name: 'Baking Soda', quantity: 0.5, unit: 'tsp', notes: 'For lightness' },
      { name: 'Good Quality Tahini', quantity: 0.5, unit: 'cup', notes: 'For sauce' },
    ],
    instructions: [
      { stepNumber: 1, title: 'Blend the Falafel Mixture', instruction: 'Drain soaked chickpeas (do NOT cook). Blend with parsley, cilantro, onion, garlic, cumin, coriander, salt, and baking soda. Blend until crumbly, not smooth. Chill 30 minutes.', timerMinutes: 10 },
      { stepNumber: 2, title: 'Make Tahini Sauce', instruction: 'Whisk tahini with lemon juice, garlic, and ice water. Keep adding water until you get a smooth, pourable sauce. Season with salt.', timerMinutes: 5 },
      { stepNumber: 3, title: 'Form Falafel Balls', instruction: 'Using a falafel scoop or two wet spoons, form compact balls or flat patties. If mixture is too loose, add 1-2 tbsp flour.', timerMinutes: 8 },
      { stepNumber: 4, title: 'Fry Until Golden', instruction: 'Deep fry in 350°F (180°C) oil in batches for 3-4 minutes until deeply golden brown and crispy. Drain on a rack. Serve immediately with tahini, pita, and vegetable salad.', timerMinutes: 12 },
    ],
  },
];

const sampleRecipes = [...baseRecipes, ...additionalRecipes];

async function seedDatabase(adminUser) {
  try {
    if (!adminUser) {
      adminUser = await User.findOne({ email: 'admin@recipehaven.com' });
    }
    if (!adminUser) {
      console.warn('[Seed Database]: No admin user available for author reference. Skipping recipe seed.');
      return;
    }

    let seededCount = 0;
    for (const r of sampleRecipes) {
      const exists = await Recipe.findOne({ title: r.title });
      if (!exists) {
        await Recipe.create({
          ...r,
          author: adminUser._id,
          authorName: adminUser.name,
          authorAvatar: adminUser.avatar,
          authorContact: {
            email: adminUser.contactEmail || adminUser.email || 'admin@recipehaven.com',
            phone: adminUser.phoneNumber || '+1 (555) 382-4920',
            location: adminUser.location || 'San Francisco, CA',
            instagram: adminUser.instagram || '@recipehaven_official',
            website: adminUser.website || 'https://recipehaven.com',
          },
          averageRating: 4.7 + Number((Math.random() * 0.3).toFixed(1)),
          ratingsCount: Math.floor(Math.random() * 35) + 10,
          favoritesCount: Math.floor(Math.random() * 55) + 15,
          isPublished: true,
          status: 'approved',
          reviews: [
            {
              user: adminUser._id,
              userName: 'Chef Isabella',
              userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
              rating: 5,
              comment: 'Absolutely sensational flavors! Followed the step-by-step instructions and timing, and the texture turned out restaurant-quality.',
              createdAt: new Date(Date.now() - 86400000 * 2),
            },
            {
              user: adminUser._id,
              userName: 'Marco Rossi',
              userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
              rating: 5,
              comment: 'Simple to follow, perfectly measured ingredients, and wonderful depth of aroma. Bookmarked for my weekly dinner rotation!',
              createdAt: new Date(Date.now() - 86400000),
            },
          ],
          comments: [
            {
              user: adminUser._id,
              userName: 'CulinaryEnthusiast',
              userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
              text: 'Can I substitute one of the herbs if fresh is not in season? Loved making this!',
              createdAt: new Date(),
            },
          ],
        });
        seededCount++;
      } else {
        // Sync verified working YouTube video URL
        if (r.videoUrl && exists.videoUrl !== r.videoUrl) {
          exists.videoUrl = r.videoUrl;
          await exists.save();
        }
      }
    }

    if (seededCount > 0) {
      console.log(`[Seed Database]: Successfully seeded ${seededCount} new recipes (total recipes: ${await Recipe.countDocuments()}).`);
    } else {
      console.log(`[Seed Database]: All ${sampleRecipes.length} recipes verified and synchronized in database.`);
    }
  } catch (err) {
    console.error('[Seed Database Error]:', err.message);
  }
}

module.exports = {
  sampleRecipes,
  seedDatabase,
};

